id = "gherkin"
name = "Gherkin"
description = "Gherkin (Cucumber) language support for Zed: syntax highlighting and snippets for .feature files."
version = "0.1.0"
schema_version = 1
authors = ["Abdullah Janjua"]
repository = "https://github.com/DevAbdullahUk/cucumber-zed"
languages = ["languages/gherkin"]

[lib]

[grammars.gherkin]
repository = "https://github.com/DevAbdullahUk/tree-sitter-gherkin"
rev = "e5066ddc7c530615437bf1474dc98942274c8cb4"
