/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 48
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 30
#define ALIAS_COUNT 0
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_comment = 1,
  sym_tag = 2,
  anon_sym_Feature = 3,
  anon_sym_COLON = 4,
  anon_sym_Rule = 5,
  anon_sym_Background = 6,
  anon_sym_Scenario = 7,
  anon_sym_Given = 8,
  anon_sym_When = 9,
  anon_sym_Then = 10,
  anon_sym_And = 11,
  anon_sym_But = 12,
  anon_sym_STAR = 13,
  sym_step_text = 14,
  sym_name_line = 15,
  sym_description_line = 16,
  sym_source_file = 17,
  sym_tag_list = 18,
  sym_feature = 19,
  sym_rule_header = 20,
  sym_background = 21,
  sym_scenario = 22,
  sym_step = 23,
  sym_step_keyword = 24,
  sym_description = 25,
  aux_sym_tag_list_repeat1 = 26,
  aux_sym_feature_repeat1 = 27,
  aux_sym_background_repeat1 = 28,
  aux_sym_description_repeat1 = 29,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [sym_tag] = "tag",
  [anon_sym_Feature] = "Feature",
  [anon_sym_COLON] = ":",
  [anon_sym_Rule] = "Rule",
  [anon_sym_Background] = "Background",
  [anon_sym_Scenario] = "Scenario",
  [anon_sym_Given] = "Given",
  [anon_sym_When] = "When",
  [anon_sym_Then] = "Then",
  [anon_sym_And] = "And",
  [anon_sym_But] = "But",
  [anon_sym_STAR] = "*",
  [sym_step_text] = "step_text",
  [sym_name_line] = "name_line",
  [sym_description_line] = "description_line",
  [sym_source_file] = "source_file",
  [sym_tag_list] = "tag_list",
  [sym_feature] = "feature",
  [sym_rule_header] = "rule_header",
  [sym_background] = "background",
  [sym_scenario] = "scenario",
  [sym_step] = "step",
  [sym_step_keyword] = "step_keyword",
  [sym_description] = "description",
  [aux_sym_tag_list_repeat1] = "tag_list_repeat1",
  [aux_sym_feature_repeat1] = "feature_repeat1",
  [aux_sym_background_repeat1] = "background_repeat1",
  [aux_sym_description_repeat1] = "description_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [sym_tag] = sym_tag,
  [anon_sym_Feature] = anon_sym_Feature,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_Rule] = anon_sym_Rule,
  [anon_sym_Background] = anon_sym_Background,
  [anon_sym_Scenario] = anon_sym_Scenario,
  [anon_sym_Given] = anon_sym_Given,
  [anon_sym_When] = anon_sym_When,
  [anon_sym_Then] = anon_sym_Then,
  [anon_sym_And] = anon_sym_And,
  [anon_sym_But] = anon_sym_But,
  [anon_sym_STAR] = anon_sym_STAR,
  [sym_step_text] = sym_step_text,
  [sym_name_line] = sym_name_line,
  [sym_description_line] = sym_description_line,
  [sym_source_file] = sym_source_file,
  [sym_tag_list] = sym_tag_list,
  [sym_feature] = sym_feature,
  [sym_rule_header] = sym_rule_header,
  [sym_background] = sym_background,
  [sym_scenario] = sym_scenario,
  [sym_step] = sym_step,
  [sym_step_keyword] = sym_step_keyword,
  [sym_description] = sym_description,
  [aux_sym_tag_list_repeat1] = aux_sym_tag_list_repeat1,
  [aux_sym_feature_repeat1] = aux_sym_feature_repeat1,
  [aux_sym_background_repeat1] = aux_sym_background_repeat1,
  [aux_sym_description_repeat1] = aux_sym_description_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_Feature] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Rule] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Background] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Scenario] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Given] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_When] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Then] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_And] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_But] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [sym_step_text] = {
    .visible = true,
    .named = true,
  },
  [sym_name_line] = {
    .visible = true,
    .named = true,
  },
  [sym_description_line] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_list] = {
    .visible = true,
    .named = true,
  },
  [sym_feature] = {
    .visible = true,
    .named = true,
  },
  [sym_rule_header] = {
    .visible = true,
    .named = true,
  },
  [sym_background] = {
    .visible = true,
    .named = true,
  },
  [sym_scenario] = {
    .visible = true,
    .named = true,
  },
  [sym_step] = {
    .visible = true,
    .named = true,
  },
  [sym_step_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_description] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_tag_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_feature_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_background_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_description_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_keyword = 1,
  field_name = 2,
  field_text = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_keyword] = "keyword",
  [field_name] = "name",
  [field_text] = "text",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 2},
  [1] =
    {field_keyword, 0},
    {field_text, 1},
  [3] =
    {field_name, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 22,
  [25] = 23,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(45);
      ADVANCE_MAP(
        '#', 46,
        '*', 58,
        ':', 49,
        '@', 42,
        'A', 25,
        'B', 4,
        'F', 11,
        'G', 21,
        'R', 38,
        'S', 8,
        'T', 19,
        'W', 20,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '#') ADVANCE(46);
      if (lookahead == '@') ADVANCE(42);
      if (lookahead == 'B') ADVANCE(92);
      if (lookahead == 'R') ADVANCE(109);
      if (lookahead == 'S') ADVANCE(94);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(90);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '|' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(112);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(2);
      if (lookahead == '#') ADVANCE(46);
      if (lookahead == '@') ADVANCE(42);
      if (lookahead == 'R') ADVANCE(109);
      if (lookahead == 'S') ADVANCE(94);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '|' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(112);
      END_STATE();
    case 3:
      if (lookahead == '\n') SKIP(3);
      if (lookahead == '#') ADVANCE(46);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(60);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(7);
      if (lookahead == 'u') ADVANCE(36);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(37);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(34);
      END_STATE();
    case 7:
      if (lookahead == 'c') ADVANCE(23);
      END_STATE();
    case 8:
      if (lookahead == 'c') ADVANCE(14);
      END_STATE();
    case 9:
      if (lookahead == 'd') ADVANCE(56);
      END_STATE();
    case 10:
      if (lookahead == 'd') ADVANCE(51);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(5);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(50);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(48);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(30);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(26);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(27);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(28);
      END_STATE();
    case 18:
      if (lookahead == 'g') ADVANCE(33);
      END_STATE();
    case 19:
      if (lookahead == 'h') ADVANCE(15);
      END_STATE();
    case 20:
      if (lookahead == 'h') ADVANCE(16);
      END_STATE();
    case 21:
      if (lookahead == 'i') ADVANCE(41);
      END_STATE();
    case 22:
      if (lookahead == 'i') ADVANCE(31);
      END_STATE();
    case 23:
      if (lookahead == 'k') ADVANCE(18);
      END_STATE();
    case 24:
      if (lookahead == 'l') ADVANCE(12);
      END_STATE();
    case 25:
      if (lookahead == 'n') ADVANCE(9);
      END_STATE();
    case 26:
      if (lookahead == 'n') ADVANCE(55);
      END_STATE();
    case 27:
      if (lookahead == 'n') ADVANCE(54);
      END_STATE();
    case 28:
      if (lookahead == 'n') ADVANCE(53);
      END_STATE();
    case 29:
      if (lookahead == 'n') ADVANCE(10);
      END_STATE();
    case 30:
      if (lookahead == 'n') ADVANCE(6);
      END_STATE();
    case 31:
      if (lookahead == 'o') ADVANCE(52);
      END_STATE();
    case 32:
      if (lookahead == 'o') ADVANCE(40);
      END_STATE();
    case 33:
      if (lookahead == 'r') ADVANCE(32);
      END_STATE();
    case 34:
      if (lookahead == 'r') ADVANCE(22);
      END_STATE();
    case 35:
      if (lookahead == 'r') ADVANCE(13);
      END_STATE();
    case 36:
      if (lookahead == 't') ADVANCE(57);
      END_STATE();
    case 37:
      if (lookahead == 't') ADVANCE(39);
      END_STATE();
    case 38:
      if (lookahead == 'u') ADVANCE(24);
      END_STATE();
    case 39:
      if (lookahead == 'u') ADVANCE(35);
      END_STATE();
    case 40:
      if (lookahead == 'u') ADVANCE(29);
      END_STATE();
    case 41:
      if (lookahead == 'v') ADVANCE(17);
      END_STATE();
    case 42:
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(47);
      END_STATE();
    case 43:
      if (eof) ADVANCE(45);
      if (lookahead == '\n') SKIP(43);
      if (lookahead == '#') ADVANCE(46);
      if (lookahead == '@') ADVANCE(42);
      if (lookahead == 'B') ADVANCE(92);
      if (lookahead == 'R') ADVANCE(109);
      if (lookahead == 'S') ADVANCE(94);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(90);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '|' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(112);
      END_STATE();
    case 44:
      if (eof) ADVANCE(45);
      if (lookahead == '\n') SKIP(44);
      if (lookahead == '#') ADVANCE(46);
      if (lookahead == '@') ADVANCE(42);
      if (lookahead == 'R') ADVANCE(109);
      if (lookahead == 'S') ADVANCE(94);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '|' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(112);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_tag);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_Feature);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_Rule);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_Background);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_Scenario);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_Given);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_When);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_Then);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_And);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_But);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_step_text);
      if (lookahead == '\n') SKIP(3);
      if (lookahead == '#') ADVANCE(46);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(60);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_step_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(60);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == '\n') SKIP(61);
      if (lookahead == '#') ADVANCE(46);
      if (lookahead == '*') ADVANCE(58);
      if (lookahead == '@') ADVANCE(87);
      if (lookahead == 'A') ADVANCE(79);
      if (lookahead == 'B') ADVANCE(84);
      if (lookahead == 'G') ADVANCE(73);
      if (lookahead == 'R') ADVANCE(85);
      if (lookahead == 'S') ADVANCE(64);
      if (lookahead == 'T') ADVANCE(71);
      if (lookahead == 'W') ADVANCE(72);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(61);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(88);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == '\n') SKIP(62);
      if (lookahead == '#') ADVANCE(46);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(88);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == 'a') ADVANCE(82);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(88);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == 'c') ADVANCE(67);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(88);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == 'd') ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(88);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == 'e') ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(88);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == 'e') ADVANCE(80);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(88);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == 'e') ADVANCE(76);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(88);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == 'e') ADVANCE(77);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(88);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == 'e') ADVANCE(78);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(88);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == 'h') ADVANCE(68);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(88);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == 'h') ADVANCE(69);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(88);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == 'i') ADVANCE(86);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(88);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == 'i') ADVANCE(81);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(88);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == 'l') ADVANCE(66);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(88);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == 'n') ADVANCE(55);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(88);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == 'n') ADVANCE(54);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(88);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == 'n') ADVANCE(53);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(88);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == 'n') ADVANCE(65);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(88);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == 'n') ADVANCE(63);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(88);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == 'o') ADVANCE(52);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(88);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == 'r') ADVANCE(74);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(88);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == 't') ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(88);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == 'u') ADVANCE(83);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(88);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == 'u') ADVANCE(75);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(88);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == 'v') ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(88);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(88);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(47);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(88);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_name_line);
      if (eof) ADVANCE(45);
      if (lookahead == '\n') SKIP(89);
      if (lookahead == '#') ADVANCE(46);
      if (lookahead == '*') ADVANCE(58);
      if (lookahead == '@') ADVANCE(87);
      if (lookahead == 'A') ADVANCE(79);
      if (lookahead == 'B') ADVANCE(84);
      if (lookahead == 'G') ADVANCE(73);
      if (lookahead == 'R') ADVANCE(85);
      if (lookahead == 'S') ADVANCE(64);
      if (lookahead == 'T') ADVANCE(71);
      if (lookahead == 'W') ADVANCE(72);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(61);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(88);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '#') ADVANCE(46);
      if (lookahead == '@') ADVANCE(111);
      if (lookahead == 'B') ADVANCE(92);
      if (lookahead == 'R') ADVANCE(109);
      if (lookahead == 'S') ADVANCE(94);
      if (lookahead == '"' ||
          lookahead == '|') ADVANCE(112);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(90);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(112);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == '\n') SKIP(2);
      if (lookahead == '#') ADVANCE(46);
      if (lookahead == '@') ADVANCE(111);
      if (lookahead == 'R') ADVANCE(109);
      if (lookahead == 'S') ADVANCE(94);
      if (lookahead == '"' ||
          lookahead == '|') ADVANCE(112);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(112);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'a') ADVANCE(95);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(112);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'a') ADVANCE(108);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(112);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'c') ADVANCE(98);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(112);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'c') ADVANCE(101);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(112);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'd') ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(112);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'e') ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(112);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'e') ADVANCE(104);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(112);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'g') ADVANCE(107);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(112);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'i') ADVANCE(105);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(112);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'k') ADVANCE(99);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(112);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'l') ADVANCE(97);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(112);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'n') ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(112);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'n') ADVANCE(93);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(112);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'o') ADVANCE(52);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(112);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'o') ADVANCE(110);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(112);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'r') ADVANCE(106);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(112);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'r') ADVANCE(100);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(112);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'u') ADVANCE(102);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(112);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'u') ADVANCE(103);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(112);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(112);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(47);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(112);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 43},
  [3] = {.lex_state = 89},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 44},
  [21] = {.lex_state = 44},
  [22] = {.lex_state = 43},
  [23] = {.lex_state = 43},
  [24] = {.lex_state = 44},
  [25] = {.lex_state = 44},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 62},
  [35] = {.lex_state = 62},
  [36] = {.lex_state = 62},
  [37] = {.lex_state = 62},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 3},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 3},
  [46] = {.lex_state = 62},
  [47] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_tag] = ACTIONS(1),
    [anon_sym_Feature] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_Rule] = ACTIONS(1),
    [anon_sym_Background] = ACTIONS(1),
    [anon_sym_Scenario] = ACTIONS(1),
    [anon_sym_Given] = ACTIONS(1),
    [anon_sym_When] = ACTIONS(1),
    [anon_sym_Then] = ACTIONS(1),
    [anon_sym_And] = ACTIONS(1),
    [anon_sym_But] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(33),
    [sym_tag_list] = STATE(30),
    [sym_feature] = STATE(44),
    [aux_sym_tag_list_repeat1] = STATE(27),
    [sym_comment] = ACTIONS(3),
    [sym_tag] = ACTIONS(5),
    [anon_sym_Feature] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 13,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    ACTIONS(11), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_tag,
    ACTIONS(15), 1,
      anon_sym_Rule,
    ACTIONS(17), 1,
      anon_sym_Background,
    ACTIONS(19), 1,
      anon_sym_Scenario,
    ACTIONS(21), 1,
      sym_description_line,
    STATE(12), 1,
      sym_description,
    STATE(19), 1,
      sym_background,
    STATE(23), 1,
      aux_sym_description_repeat1,
    STATE(27), 1,
      aux_sym_tag_list_repeat1,
    STATE(31), 1,
      sym_tag_list,
    STATE(16), 3,
      sym_rule_header,
      sym_scenario,
      aux_sym_feature_repeat1,
  [42] = 7,
    ACTIONS(11), 1,
      sym_comment,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    ACTIONS(29), 1,
      sym_name_line,
    STATE(45), 1,
      sym_step_keyword,
    STATE(4), 2,
      sym_step,
      aux_sym_background_repeat1,
    ACTIONS(25), 3,
      sym_tag,
      anon_sym_Rule,
      anon_sym_Scenario,
    ACTIONS(27), 6,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
      anon_sym_And,
      anon_sym_But,
      anon_sym_STAR,
  [72] = 5,
    ACTIONS(3), 1,
      sym_comment,
    STATE(45), 1,
      sym_step_keyword,
    STATE(9), 2,
      sym_step,
      aux_sym_background_repeat1,
    ACTIONS(31), 4,
      ts_builtin_sym_end,
      sym_tag,
      anon_sym_Rule,
      anon_sym_Scenario,
    ACTIONS(33), 6,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
      anon_sym_And,
      anon_sym_But,
      anon_sym_STAR,
  [97] = 5,
    ACTIONS(3), 1,
      sym_comment,
    STATE(45), 1,
      sym_step_keyword,
    STATE(8), 2,
      sym_step,
      aux_sym_background_repeat1,
    ACTIONS(35), 4,
      ts_builtin_sym_end,
      sym_tag,
      anon_sym_Rule,
      anon_sym_Scenario,
    ACTIONS(33), 6,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
      anon_sym_And,
      anon_sym_But,
      anon_sym_STAR,
  [122] = 5,
    ACTIONS(3), 1,
      sym_comment,
    STATE(45), 1,
      sym_step_keyword,
    STATE(9), 2,
      sym_step,
      aux_sym_background_repeat1,
    ACTIONS(37), 4,
      ts_builtin_sym_end,
      sym_tag,
      anon_sym_Rule,
      anon_sym_Scenario,
    ACTIONS(33), 6,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
      anon_sym_And,
      anon_sym_But,
      anon_sym_STAR,
  [147] = 5,
    ACTIONS(3), 1,
      sym_comment,
    STATE(45), 1,
      sym_step_keyword,
    STATE(6), 2,
      sym_step,
      aux_sym_background_repeat1,
    ACTIONS(39), 4,
      ts_builtin_sym_end,
      sym_tag,
      anon_sym_Rule,
      anon_sym_Scenario,
    ACTIONS(33), 6,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
      anon_sym_And,
      anon_sym_But,
      anon_sym_STAR,
  [172] = 5,
    ACTIONS(3), 1,
      sym_comment,
    STATE(45), 1,
      sym_step_keyword,
    STATE(9), 2,
      sym_step,
      aux_sym_background_repeat1,
    ACTIONS(41), 4,
      ts_builtin_sym_end,
      sym_tag,
      anon_sym_Rule,
      anon_sym_Scenario,
    ACTIONS(33), 6,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
      anon_sym_And,
      anon_sym_But,
      anon_sym_STAR,
  [197] = 5,
    ACTIONS(3), 1,
      sym_comment,
    STATE(45), 1,
      sym_step_keyword,
    STATE(9), 2,
      sym_step,
      aux_sym_background_repeat1,
    ACTIONS(43), 4,
      ts_builtin_sym_end,
      sym_tag,
      anon_sym_Rule,
      anon_sym_Scenario,
    ACTIONS(45), 6,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
      anon_sym_And,
      anon_sym_But,
      anon_sym_STAR,
  [222] = 5,
    ACTIONS(3), 1,
      sym_comment,
    STATE(45), 1,
      sym_step_keyword,
    STATE(11), 2,
      sym_step,
      aux_sym_background_repeat1,
    ACTIONS(48), 4,
      ts_builtin_sym_end,
      sym_tag,
      anon_sym_Rule,
      anon_sym_Scenario,
    ACTIONS(33), 6,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
      anon_sym_And,
      anon_sym_But,
      anon_sym_STAR,
  [247] = 5,
    ACTIONS(3), 1,
      sym_comment,
    STATE(45), 1,
      sym_step_keyword,
    STATE(9), 2,
      sym_step,
      aux_sym_background_repeat1,
    ACTIONS(50), 4,
      ts_builtin_sym_end,
      sym_tag,
      anon_sym_Rule,
      anon_sym_Scenario,
    ACTIONS(33), 6,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
      anon_sym_And,
      anon_sym_But,
      anon_sym_STAR,
  [272] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym_tag,
    ACTIONS(52), 1,
      ts_builtin_sym_end,
    ACTIONS(54), 1,
      anon_sym_Rule,
    ACTIONS(56), 1,
      anon_sym_Background,
    ACTIONS(58), 1,
      anon_sym_Scenario,
    STATE(15), 1,
      sym_background,
    STATE(27), 1,
      aux_sym_tag_list_repeat1,
    STATE(31), 1,
      sym_tag_list,
    STATE(14), 3,
      sym_rule_header,
      sym_scenario,
      aux_sym_feature_repeat1,
  [305] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(60), 10,
      ts_builtin_sym_end,
      sym_tag,
      anon_sym_Rule,
      anon_sym_Scenario,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
      anon_sym_And,
      anon_sym_But,
      anon_sym_STAR,
  [321] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym_tag,
    ACTIONS(54), 1,
      anon_sym_Rule,
    ACTIONS(58), 1,
      anon_sym_Scenario,
    ACTIONS(62), 1,
      ts_builtin_sym_end,
    STATE(27), 1,
      aux_sym_tag_list_repeat1,
    STATE(31), 1,
      sym_tag_list,
    STATE(18), 3,
      sym_rule_header,
      sym_scenario,
      aux_sym_feature_repeat1,
  [348] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym_tag,
    ACTIONS(54), 1,
      anon_sym_Rule,
    ACTIONS(58), 1,
      anon_sym_Scenario,
    ACTIONS(62), 1,
      ts_builtin_sym_end,
    STATE(27), 1,
      aux_sym_tag_list_repeat1,
    STATE(31), 1,
      sym_tag_list,
    STATE(17), 3,
      sym_rule_header,
      sym_scenario,
      aux_sym_feature_repeat1,
  [375] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym_tag,
    ACTIONS(52), 1,
      ts_builtin_sym_end,
    ACTIONS(54), 1,
      anon_sym_Rule,
    ACTIONS(58), 1,
      anon_sym_Scenario,
    STATE(27), 1,
      aux_sym_tag_list_repeat1,
    STATE(31), 1,
      sym_tag_list,
    STATE(18), 3,
      sym_rule_header,
      sym_scenario,
      aux_sym_feature_repeat1,
  [402] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym_tag,
    ACTIONS(54), 1,
      anon_sym_Rule,
    ACTIONS(58), 1,
      anon_sym_Scenario,
    ACTIONS(64), 1,
      ts_builtin_sym_end,
    STATE(27), 1,
      aux_sym_tag_list_repeat1,
    STATE(31), 1,
      sym_tag_list,
    STATE(18), 3,
      sym_rule_header,
      sym_scenario,
      aux_sym_feature_repeat1,
  [429] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 1,
      ts_builtin_sym_end,
    ACTIONS(68), 1,
      sym_tag,
    ACTIONS(71), 1,
      anon_sym_Rule,
    ACTIONS(74), 1,
      anon_sym_Scenario,
    STATE(27), 1,
      aux_sym_tag_list_repeat1,
    STATE(31), 1,
      sym_tag_list,
    STATE(18), 3,
      sym_rule_header,
      sym_scenario,
      aux_sym_feature_repeat1,
  [456] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym_tag,
    ACTIONS(52), 1,
      ts_builtin_sym_end,
    ACTIONS(54), 1,
      anon_sym_Rule,
    ACTIONS(58), 1,
      anon_sym_Scenario,
    STATE(27), 1,
      aux_sym_tag_list_repeat1,
    STATE(31), 1,
      sym_tag_list,
    STATE(14), 3,
      sym_rule_header,
      sym_scenario,
      aux_sym_feature_repeat1,
  [483] = 6,
    ACTIONS(11), 1,
      sym_comment,
    ACTIONS(77), 1,
      ts_builtin_sym_end,
    ACTIONS(81), 1,
      sym_description_line,
    STATE(25), 1,
      aux_sym_description_repeat1,
    STATE(28), 1,
      sym_description,
    ACTIONS(79), 3,
      sym_tag,
      anon_sym_Rule,
      anon_sym_Scenario,
  [504] = 6,
    ACTIONS(11), 1,
      sym_comment,
    ACTIONS(81), 1,
      sym_description_line,
    ACTIONS(83), 1,
      ts_builtin_sym_end,
    STATE(25), 1,
      aux_sym_description_repeat1,
    STATE(29), 1,
      sym_description,
    ACTIONS(85), 3,
      sym_tag,
      anon_sym_Rule,
      anon_sym_Scenario,
  [525] = 5,
    ACTIONS(11), 1,
      sym_comment,
    ACTIONS(87), 1,
      ts_builtin_sym_end,
    ACTIONS(91), 1,
      sym_description_line,
    STATE(22), 1,
      aux_sym_description_repeat1,
    ACTIONS(89), 4,
      sym_tag,
      anon_sym_Rule,
      anon_sym_Background,
      anon_sym_Scenario,
  [544] = 5,
    ACTIONS(11), 1,
      sym_comment,
    ACTIONS(94), 1,
      ts_builtin_sym_end,
    ACTIONS(98), 1,
      sym_description_line,
    STATE(22), 1,
      aux_sym_description_repeat1,
    ACTIONS(96), 4,
      sym_tag,
      anon_sym_Rule,
      anon_sym_Background,
      anon_sym_Scenario,
  [563] = 5,
    ACTIONS(11), 1,
      sym_comment,
    ACTIONS(87), 1,
      ts_builtin_sym_end,
    ACTIONS(100), 1,
      sym_description_line,
    STATE(24), 1,
      aux_sym_description_repeat1,
    ACTIONS(89), 3,
      sym_tag,
      anon_sym_Rule,
      anon_sym_Scenario,
  [581] = 5,
    ACTIONS(11), 1,
      sym_comment,
    ACTIONS(94), 1,
      ts_builtin_sym_end,
    ACTIONS(103), 1,
      sym_description_line,
    STATE(24), 1,
      aux_sym_description_repeat1,
    ACTIONS(96), 3,
      sym_tag,
      anon_sym_Rule,
      anon_sym_Scenario,
  [599] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 1,
      sym_tag,
    STATE(26), 1,
      aux_sym_tag_list_repeat1,
    ACTIONS(108), 3,
      anon_sym_Feature,
      anon_sym_Rule,
      anon_sym_Scenario,
  [614] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 1,
      sym_tag,
    STATE(26), 1,
      aux_sym_tag_list_repeat1,
    ACTIONS(112), 3,
      anon_sym_Feature,
      anon_sym_Rule,
      anon_sym_Scenario,
  [629] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 4,
      ts_builtin_sym_end,
      sym_tag,
      anon_sym_Rule,
      anon_sym_Scenario,
  [639] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(116), 4,
      ts_builtin_sym_end,
      sym_tag,
      anon_sym_Rule,
      anon_sym_Scenario,
  [649] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_Feature,
    STATE(47), 1,
      sym_feature,
  [659] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 1,
      anon_sym_Rule,
    ACTIONS(120), 1,
      anon_sym_Scenario,
  [669] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(122), 1,
      anon_sym_COLON,
  [676] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(124), 1,
      ts_builtin_sym_end,
  [683] = 2,
    ACTIONS(11), 1,
      sym_comment,
    ACTIONS(126), 1,
      sym_name_line,
  [690] = 2,
    ACTIONS(11), 1,
      sym_comment,
    ACTIONS(128), 1,
      sym_name_line,
  [697] = 2,
    ACTIONS(11), 1,
      sym_comment,
    ACTIONS(130), 1,
      sym_name_line,
  [704] = 2,
    ACTIONS(11), 1,
      sym_comment,
    ACTIONS(132), 1,
      sym_name_line,
  [711] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(134), 1,
      anon_sym_COLON,
  [718] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(136), 1,
      anon_sym_COLON,
  [725] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 1,
      anon_sym_COLON,
  [732] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(140), 1,
      anon_sym_COLON,
  [739] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 1,
      anon_sym_COLON,
  [746] = 2,
    ACTIONS(11), 1,
      sym_comment,
    ACTIONS(144), 1,
      sym_step_text,
  [753] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 1,
      ts_builtin_sym_end,
  [760] = 2,
    ACTIONS(11), 1,
      sym_comment,
    ACTIONS(148), 1,
      sym_step_text,
  [767] = 2,
    ACTIONS(11), 1,
      sym_comment,
    ACTIONS(150), 1,
      sym_name_line,
  [774] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 42,
  [SMALL_STATE(4)] = 72,
  [SMALL_STATE(5)] = 97,
  [SMALL_STATE(6)] = 122,
  [SMALL_STATE(7)] = 147,
  [SMALL_STATE(8)] = 172,
  [SMALL_STATE(9)] = 197,
  [SMALL_STATE(10)] = 222,
  [SMALL_STATE(11)] = 247,
  [SMALL_STATE(12)] = 272,
  [SMALL_STATE(13)] = 305,
  [SMALL_STATE(14)] = 321,
  [SMALL_STATE(15)] = 348,
  [SMALL_STATE(16)] = 375,
  [SMALL_STATE(17)] = 402,
  [SMALL_STATE(18)] = 429,
  [SMALL_STATE(19)] = 456,
  [SMALL_STATE(20)] = 483,
  [SMALL_STATE(21)] = 504,
  [SMALL_STATE(22)] = 525,
  [SMALL_STATE(23)] = 544,
  [SMALL_STATE(24)] = 563,
  [SMALL_STATE(25)] = 581,
  [SMALL_STATE(26)] = 599,
  [SMALL_STATE(27)] = 614,
  [SMALL_STATE(28)] = 629,
  [SMALL_STATE(29)] = 639,
  [SMALL_STATE(30)] = 649,
  [SMALL_STATE(31)] = 659,
  [SMALL_STATE(32)] = 669,
  [SMALL_STATE(33)] = 676,
  [SMALL_STATE(34)] = 683,
  [SMALL_STATE(35)] = 690,
  [SMALL_STATE(36)] = 697,
  [SMALL_STATE(37)] = 704,
  [SMALL_STATE(38)] = 711,
  [SMALL_STATE(39)] = 718,
  [SMALL_STATE(40)] = 725,
  [SMALL_STATE(41)] = 732,
  [SMALL_STATE(42)] = 739,
  [SMALL_STATE(43)] = 746,
  [SMALL_STATE(44)] = 753,
  [SMALL_STATE(45)] = 760,
  [SMALL_STATE(46)] = 767,
  [SMALL_STATE(47)] = 774,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_feature, 3, 0, 1),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_background, 2, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_background, 2, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_background, 3, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_background, 3, 0, 1),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scenario, 4, 0, 1),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scenario, 3, 0, 1),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_background, 4, 0, 1),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_background_repeat1, 2, 0, 0),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_background_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scenario, 4, 0, 3),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scenario, 5, 0, 3),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_feature, 4, 0, 1),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_step, 2, 0, 2),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_feature, 5, 0, 1),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_feature, 6, 0, 1),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_feature_repeat1, 2, 0, 0),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_feature_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_feature_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_feature_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule_header, 3, 0, 1),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_rule_header, 3, 0, 1),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule_header, 4, 0, 3),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_rule_header, 4, 0, 3),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_description_repeat1, 2, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_description_repeat1, 2, 0, 0),
  [91] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_description_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_description, 1, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_description, 1, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [100] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_description_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [103] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [105] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tag_list_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tag_list_repeat1, 2, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_list, 1, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule_header, 4, 0, 1),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule_header, 5, 0, 3),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [124] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [126] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [128] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [130] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [132] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_step_keyword, 1, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [150] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_gherkin(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "gherkin",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
