/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 82
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 40
#define ALIAS_COUNT 0
#define TOKEN_COUNT 22
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_comment = 1,
  sym_tag = 2,
  anon_sym_Feature = 3,
  anon_sym_COLON = 4,
  anon_sym_Rule = 5,
  anon_sym_Background = 6,
  anon_sym_Scenario = 7,
  anon_sym_ScenarioOutline = 8,
  anon_sym_Examples = 9,
  anon_sym_Given = 10,
  anon_sym_When = 11,
  anon_sym_Then = 12,
  anon_sym_And = 13,
  anon_sym_But = 14,
  anon_sym_STAR = 15,
  sym_step_text = 16,
  sym_name_line = 17,
  sym_description_line = 18,
  anon_sym_PIPE = 19,
  sym_table_cell = 20,
  sym_doc_string = 21,
  sym_source_file = 22,
  sym_tag_list = 23,
  sym_feature = 24,
  sym_rule_header = 25,
  sym_background = 26,
  sym_scenario = 27,
  sym_examples = 28,
  sym_step = 29,
  sym_step_keyword = 30,
  sym_description = 31,
  sym_data_table = 32,
  sym_table_row = 33,
  aux_sym_tag_list_repeat1 = 34,
  aux_sym_feature_repeat1 = 35,
  aux_sym_background_repeat1 = 36,
  aux_sym_description_repeat1 = 37,
  aux_sym_data_table_repeat1 = 38,
  aux_sym_table_row_repeat1 = 39,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [sym_tag] = "tag",
  [anon_sym_Feature] = "Feature",
  [anon_sym_COLON] = ":",
  [anon_sym_Rule] = "Rule",
  [anon_sym_Background] = "Background",
  [anon_sym_Scenario] = "Scenario",
  [anon_sym_ScenarioOutline] = "Scenario Outline",
  [anon_sym_Examples] = "Examples",
  [anon_sym_Given] = "Given",
  [anon_sym_When] = "When",
  [anon_sym_Then] = "Then",
  [anon_sym_And] = "And",
  [anon_sym_But] = "But",
  [anon_sym_STAR] = "*",
  [sym_step_text] = "step_text",
  [sym_name_line] = "name_line",
  [sym_description_line] = "description_line",
  [anon_sym_PIPE] = "|",
  [sym_table_cell] = "table_cell",
  [sym_doc_string] = "doc_string",
  [sym_source_file] = "source_file",
  [sym_tag_list] = "tag_list",
  [sym_feature] = "feature",
  [sym_rule_header] = "rule_header",
  [sym_background] = "background",
  [sym_scenario] = "scenario",
  [sym_examples] = "examples",
  [sym_step] = "step",
  [sym_step_keyword] = "step_keyword",
  [sym_description] = "description",
  [sym_data_table] = "data_table",
  [sym_table_row] = "table_row",
  [aux_sym_tag_list_repeat1] = "tag_list_repeat1",
  [aux_sym_feature_repeat1] = "feature_repeat1",
  [aux_sym_background_repeat1] = "background_repeat1",
  [aux_sym_description_repeat1] = "description_repeat1",
  [aux_sym_data_table_repeat1] = "data_table_repeat1",
  [aux_sym_table_row_repeat1] = "table_row_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [sym_tag] = sym_tag,
  [anon_sym_Feature] = anon_sym_Feature,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_Rule] = anon_sym_Rule,
  [anon_sym_Background] = anon_sym_Background,
  [anon_sym_Scenario] = anon_sym_Scenario,
  [anon_sym_ScenarioOutline] = anon_sym_ScenarioOutline,
  [anon_sym_Examples] = anon_sym_Examples,
  [anon_sym_Given] = anon_sym_Given,
  [anon_sym_When] = anon_sym_When,
  [anon_sym_Then] = anon_sym_Then,
  [anon_sym_And] = anon_sym_And,
  [anon_sym_But] = anon_sym_But,
  [anon_sym_STAR] = anon_sym_STAR,
  [sym_step_text] = sym_step_text,
  [sym_name_line] = sym_name_line,
  [sym_description_line] = sym_description_line,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [sym_table_cell] = sym_table_cell,
  [sym_doc_string] = sym_doc_string,
  [sym_source_file] = sym_source_file,
  [sym_tag_list] = sym_tag_list,
  [sym_feature] = sym_feature,
  [sym_rule_header] = sym_rule_header,
  [sym_background] = sym_background,
  [sym_scenario] = sym_scenario,
  [sym_examples] = sym_examples,
  [sym_step] = sym_step,
  [sym_step_keyword] = sym_step_keyword,
  [sym_description] = sym_description,
  [sym_data_table] = sym_data_table,
  [sym_table_row] = sym_table_row,
  [aux_sym_tag_list_repeat1] = aux_sym_tag_list_repeat1,
  [aux_sym_feature_repeat1] = aux_sym_feature_repeat1,
  [aux_sym_background_repeat1] = aux_sym_background_repeat1,
  [aux_sym_description_repeat1] = aux_sym_description_repeat1,
  [aux_sym_data_table_repeat1] = aux_sym_data_table_repeat1,
  [aux_sym_table_row_repeat1] = aux_sym_table_row_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_Feature] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Rule] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Background] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Scenario] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ScenarioOutline] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Examples] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Given] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_When] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Then] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_And] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_But] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [sym_step_text] = {
    .visible = true,
    .named = true,
  },
  [sym_name_line] = {
    .visible = true,
    .named = true,
  },
  [sym_description_line] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [sym_table_cell] = {
    .visible = true,
    .named = true,
  },
  [sym_doc_string] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_list] = {
    .visible = true,
    .named = true,
  },
  [sym_feature] = {
    .visible = true,
    .named = true,
  },
  [sym_rule_header] = {
    .visible = true,
    .named = true,
  },
  [sym_background] = {
    .visible = true,
    .named = true,
  },
  [sym_scenario] = {
    .visible = true,
    .named = true,
  },
  [sym_examples] = {
    .visible = true,
    .named = true,
  },
  [sym_step] = {
    .visible = true,
    .named = true,
  },
  [sym_step_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_description] = {
    .visible = true,
    .named = true,
  },
  [sym_data_table] = {
    .visible = true,
    .named = true,
  },
  [sym_table_row] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_tag_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_feature_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_background_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_description_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_data_table_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_table_row_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_keyword = 1,
  field_name = 2,
  field_text = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_keyword] = "keyword",
  [field_name] = "name",
  [field_text] = "text",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 2},
  [1] =
    {field_keyword, 0},
    {field_text, 1},
  [3] =
    {field_name, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 14,
  [19] = 11,
  [20] = 12,
  [21] = 13,
  [22] = 10,
  [23] = 23,
  [24] = 23,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 13,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 10,
  [39] = 11,
  [40] = 12,
  [41] = 23,
  [42] = 35,
  [43] = 37,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 57,
  [60] = 57,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 65,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 65,
  [78] = 78,
  [79] = 79,
  [80] = 78,
  [81] = 81,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(64);
      ADVANCE_MAP(
        '"', 6,
        '#', 66,
        '*', 84,
        ':', 70,
        '@', 61,
        'A', 38,
        'B', 11,
        'E', 60,
        'F', 23,
        'G', 30,
        'R', 55,
        'S', 15,
        'T', 28,
        'W', 29,
        '|', 154,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '#') ADVANCE(66);
      if (lookahead == '@') ADVANCE(61);
      if (lookahead == 'B') ADVANCE(127);
      if (lookahead == 'R') ADVANCE(149);
      if (lookahead == 'S') ADVANCE(129);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(124);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '|' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(153);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(2);
      if (lookahead == '#') ADVANCE(66);
      if (lookahead == '@') ADVANCE(61);
      if (lookahead == 'R') ADVANCE(149);
      if (lookahead == 'S') ADVANCE(129);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(125);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '|' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(153);
      END_STATE();
    case 3:
      if (lookahead == '\n') SKIP(3);
      if (lookahead == '#') ADVANCE(66);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(85);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(86);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(8);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(202);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(8);
      END_STATE();
    case 6:
      if (lookahead == '"') ADVANCE(4);
      END_STATE();
    case 7:
      if (lookahead == '"') ADVANCE(5);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(8);
      END_STATE();
    case 8:
      if (lookahead == '"') ADVANCE(7);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead == 'O') ADVANCE(57);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(37);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(14);
      if (lookahead == 'u') ADVANCE(52);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(53);
      END_STATE();
    case 13:
      if (lookahead == 'a') ADVANCE(49);
      END_STATE();
    case 14:
      if (lookahead == 'c') ADVANCE(33);
      END_STATE();
    case 15:
      if (lookahead == 'c') ADVANCE(22);
      END_STATE();
    case 16:
      if (lookahead == 'd') ADVANCE(82);
      END_STATE();
    case 17:
      if (lookahead == 'd') ADVANCE(72);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(71);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(51);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(69);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(77);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(43);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(12);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(39);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(40);
      END_STATE();
    case 26:
      if (lookahead == 'e') ADVANCE(41);
      END_STATE();
    case 27:
      if (lookahead == 'g') ADVANCE(48);
      END_STATE();
    case 28:
      if (lookahead == 'h') ADVANCE(24);
      END_STATE();
    case 29:
      if (lookahead == 'h') ADVANCE(25);
      END_STATE();
    case 30:
      if (lookahead == 'i') ADVANCE(59);
      END_STATE();
    case 31:
      if (lookahead == 'i') ADVANCE(45);
      END_STATE();
    case 32:
      if (lookahead == 'i') ADVANCE(44);
      END_STATE();
    case 33:
      if (lookahead == 'k') ADVANCE(27);
      END_STATE();
    case 34:
      if (lookahead == 'l') ADVANCE(32);
      END_STATE();
    case 35:
      if (lookahead == 'l') ADVANCE(18);
      END_STATE();
    case 36:
      if (lookahead == 'l') ADVANCE(19);
      END_STATE();
    case 37:
      if (lookahead == 'm') ADVANCE(47);
      END_STATE();
    case 38:
      if (lookahead == 'n') ADVANCE(16);
      END_STATE();
    case 39:
      if (lookahead == 'n') ADVANCE(81);
      END_STATE();
    case 40:
      if (lookahead == 'n') ADVANCE(80);
      END_STATE();
    case 41:
      if (lookahead == 'n') ADVANCE(79);
      END_STATE();
    case 42:
      if (lookahead == 'n') ADVANCE(17);
      END_STATE();
    case 43:
      if (lookahead == 'n') ADVANCE(13);
      END_STATE();
    case 44:
      if (lookahead == 'n') ADVANCE(21);
      END_STATE();
    case 45:
      if (lookahead == 'o') ADVANCE(73);
      END_STATE();
    case 46:
      if (lookahead == 'o') ADVANCE(58);
      END_STATE();
    case 47:
      if (lookahead == 'p') ADVANCE(36);
      END_STATE();
    case 48:
      if (lookahead == 'r') ADVANCE(46);
      END_STATE();
    case 49:
      if (lookahead == 'r') ADVANCE(31);
      END_STATE();
    case 50:
      if (lookahead == 'r') ADVANCE(20);
      END_STATE();
    case 51:
      if (lookahead == 's') ADVANCE(78);
      END_STATE();
    case 52:
      if (lookahead == 't') ADVANCE(83);
      END_STATE();
    case 53:
      if (lookahead == 't') ADVANCE(56);
      END_STATE();
    case 54:
      if (lookahead == 't') ADVANCE(34);
      END_STATE();
    case 55:
      if (lookahead == 'u') ADVANCE(35);
      END_STATE();
    case 56:
      if (lookahead == 'u') ADVANCE(50);
      END_STATE();
    case 57:
      if (lookahead == 'u') ADVANCE(54);
      END_STATE();
    case 58:
      if (lookahead == 'u') ADVANCE(42);
      END_STATE();
    case 59:
      if (lookahead == 'v') ADVANCE(26);
      END_STATE();
    case 60:
      if (lookahead == 'x') ADVANCE(10);
      END_STATE();
    case 61:
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(68);
      END_STATE();
    case 62:
      if (eof) ADVANCE(64);
      if (lookahead == '\n') SKIP(62);
      if (lookahead == '#') ADVANCE(66);
      if (lookahead == '@') ADVANCE(61);
      if (lookahead == 'B') ADVANCE(127);
      if (lookahead == 'R') ADVANCE(149);
      if (lookahead == 'S') ADVANCE(129);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(124);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '|' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(153);
      END_STATE();
    case 63:
      if (eof) ADVANCE(64);
      if (lookahead == '\n') SKIP(63);
      if (lookahead == '#') ADVANCE(66);
      if (lookahead == '@') ADVANCE(61);
      if (lookahead == 'R') ADVANCE(149);
      if (lookahead == 'S') ADVANCE(129);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(125);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '|' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(153);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '|') ADVANCE(66);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(65);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(66);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_tag);
      if (lookahead == '|') ADVANCE(68);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(67);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_tag);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(68);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_Feature);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_Rule);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_Background);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_Scenario);
      if (lookahead == ' ') ADVANCE(9);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_Scenario);
      if (lookahead == ' ') ADVANCE(90);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_Scenario);
      if (lookahead == ' ') ADVANCE(126);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_Scenario);
      if (lookahead == ' ') ADVANCE(159);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_ScenarioOutline);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_Examples);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_Given);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_When);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_Then);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_And);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_But);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_step_text);
      if (lookahead == '\n') SKIP(3);
      if (lookahead == '#') ADVANCE(66);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(85);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(86);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_step_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(86);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == '\n') SKIP(87);
      if (lookahead == '#') ADVANCE(66);
      if (lookahead == '*') ADVANCE(84);
      if (lookahead == '@') ADVANCE(121);
      if (lookahead == 'A') ADVANCE(110);
      if (lookahead == 'B') ADVANCE(117);
      if (lookahead == 'G') ADVANCE(102);
      if (lookahead == 'R') ADVANCE(118);
      if (lookahead == 'S') ADVANCE(92);
      if (lookahead == 'T') ADVANCE(100);
      if (lookahead == 'W') ADVANCE(101);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(87);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(122);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == '\n') SKIP(88);
      if (lookahead == '#') ADVANCE(66);
      if (lookahead == '|') ADVANCE(154);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(88);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(122);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == '\n') SKIP(89);
      if (lookahead == '#') ADVANCE(66);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(89);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(122);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == 'O') ADVANCE(119);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(122);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == 'a') ADVANCE(114);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(122);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == 'c') ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(122);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == 'd') ADVANCE(82);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(122);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == 'e') ADVANCE(71);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(122);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == 'e') ADVANCE(77);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(122);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == 'e') ADVANCE(111);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(122);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == 'e') ADVANCE(107);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(122);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == 'e') ADVANCE(108);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(122);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == 'e') ADVANCE(109);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(122);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == 'h') ADVANCE(97);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(122);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == 'h') ADVANCE(98);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(122);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == 'i') ADVANCE(120);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(122);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == 'i') ADVANCE(113);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(122);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == 'i') ADVANCE(112);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(122);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == 'l') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(122);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == 'l') ADVANCE(104);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(122);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == 'n') ADVANCE(81);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(122);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == 'n') ADVANCE(80);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(122);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == 'n') ADVANCE(79);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(122);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == 'n') ADVANCE(93);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(122);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == 'n') ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(122);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == 'n') ADVANCE(95);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(122);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == 'o') ADVANCE(74);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(122);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == 'r') ADVANCE(103);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(122);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == 't') ADVANCE(83);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(122);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == 't') ADVANCE(106);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(122);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == 'u') ADVANCE(115);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(122);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == 'u') ADVANCE(105);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(122);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == 'u') ADVANCE(116);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(122);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == 'v') ADVANCE(99);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(122);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(122);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(68);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(122);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_name_line);
      if (eof) ADVANCE(64);
      if (lookahead == '\n') SKIP(123);
      if (lookahead == '#') ADVANCE(66);
      if (lookahead == '*') ADVANCE(84);
      if (lookahead == '@') ADVANCE(121);
      if (lookahead == 'A') ADVANCE(110);
      if (lookahead == 'B') ADVANCE(117);
      if (lookahead == 'G') ADVANCE(102);
      if (lookahead == 'R') ADVANCE(118);
      if (lookahead == 'S') ADVANCE(92);
      if (lookahead == 'T') ADVANCE(100);
      if (lookahead == 'W') ADVANCE(101);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(87);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(122);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '#') ADVANCE(66);
      if (lookahead == '@') ADVANCE(152);
      if (lookahead == 'B') ADVANCE(127);
      if (lookahead == 'R') ADVANCE(149);
      if (lookahead == 'S') ADVANCE(129);
      if (lookahead == '"' ||
          lookahead == '|') ADVANCE(153);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(124);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(153);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == '\n') SKIP(2);
      if (lookahead == '#') ADVANCE(66);
      if (lookahead == '@') ADVANCE(152);
      if (lookahead == 'R') ADVANCE(149);
      if (lookahead == 'S') ADVANCE(129);
      if (lookahead == '"' ||
          lookahead == '|') ADVANCE(153);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(125);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(153);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'O') ADVANCE(150);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(153);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'a') ADVANCE(130);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(153);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'a') ADVANCE(147);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(153);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'c') ADVANCE(134);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(153);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'c') ADVANCE(138);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(153);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'd') ADVANCE(72);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(153);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'e') ADVANCE(71);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(153);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'e') ADVANCE(77);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(153);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'e') ADVANCE(142);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(153);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'g') ADVANCE(146);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(153);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'i') ADVANCE(145);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(153);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'i') ADVANCE(143);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(153);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'k') ADVANCE(135);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(153);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'l') ADVANCE(132);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(153);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'l') ADVANCE(137);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(153);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'n') ADVANCE(131);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(153);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'n') ADVANCE(128);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(153);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'n') ADVANCE(133);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(153);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'o') ADVANCE(151);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(153);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'o') ADVANCE(75);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(153);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'r') ADVANCE(144);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(153);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'r') ADVANCE(136);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(153);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 't') ADVANCE(140);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(153);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'u') ADVANCE(139);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(153);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'u') ADVANCE(148);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(153);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'u') ADVANCE(141);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(153);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(153);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(68);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(153);
      END_STATE();
    case 154:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(sym_table_cell);
      if (lookahead == '\n') SKIP(155);
      if (lookahead == '#') ADVANCE(65);
      if (lookahead == '*') ADVANCE(84);
      if (lookahead == '@') ADVANCE(197);
      if (lookahead == 'A') ADVANCE(183);
      if (lookahead == 'B') ADVANCE(192);
      if (lookahead == 'E') ADVANCE(196);
      if (lookahead == 'G') ADVANCE(173);
      if (lookahead == 'R') ADVANCE(193);
      if (lookahead == 'S') ADVANCE(162);
      if (lookahead == 'T') ADVANCE(171);
      if (lookahead == 'W') ADVANCE(172);
      if (lookahead == '|') ADVANCE(154);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(155);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(198);
      END_STATE();
    case 156:
      ACCEPT_TOKEN(sym_table_cell);
      if (lookahead == '\n') SKIP(156);
      if (lookahead == '#') ADVANCE(65);
      if (lookahead == '*') ADVANCE(84);
      if (lookahead == '@') ADVANCE(197);
      if (lookahead == 'A') ADVANCE(183);
      if (lookahead == 'B') ADVANCE(192);
      if (lookahead == 'G') ADVANCE(173);
      if (lookahead == 'R') ADVANCE(193);
      if (lookahead == 'S') ADVANCE(162);
      if (lookahead == 'T') ADVANCE(171);
      if (lookahead == 'W') ADVANCE(172);
      if (lookahead == '|') ADVANCE(154);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(156);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(198);
      END_STATE();
    case 157:
      ACCEPT_TOKEN(sym_table_cell);
      if (lookahead == '\n') SKIP(157);
      if (lookahead == '#') ADVANCE(65);
      if (lookahead == '@') ADVANCE(197);
      if (lookahead == 'R') ADVANCE(193);
      if (lookahead == 'S') ADVANCE(162);
      if (lookahead == '|') ADVANCE(154);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(157);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(198);
      END_STATE();
    case 158:
      ACCEPT_TOKEN(sym_table_cell);
      if (lookahead == '\n') SKIP(158);
      if (lookahead == '#') ADVANCE(65);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(158);
      if (lookahead != 0 &&
          lookahead != '|' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(198);
      END_STATE();
    case 159:
      ACCEPT_TOKEN(sym_table_cell);
      if (lookahead == 'O') ADVANCE(194);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '|' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(198);
      END_STATE();
    case 160:
      ACCEPT_TOKEN(sym_table_cell);
      if (lookahead == 'a') ADVANCE(179);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '|' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(198);
      END_STATE();
    case 161:
      ACCEPT_TOKEN(sym_table_cell);
      if (lookahead == 'a') ADVANCE(188);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '|' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(198);
      END_STATE();
    case 162:
      ACCEPT_TOKEN(sym_table_cell);
      if (lookahead == 'c') ADVANCE(167);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '|' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(198);
      END_STATE();
    case 163:
      ACCEPT_TOKEN(sym_table_cell);
      if (lookahead == 'd') ADVANCE(82);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '|' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(198);
      END_STATE();
    case 164:
      ACCEPT_TOKEN(sym_table_cell);
      if (lookahead == 'e') ADVANCE(71);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '|' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(198);
      END_STATE();
    case 165:
      ACCEPT_TOKEN(sym_table_cell);
      if (lookahead == 'e') ADVANCE(77);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '|' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(198);
      END_STATE();
    case 166:
      ACCEPT_TOKEN(sym_table_cell);
      if (lookahead == 'e') ADVANCE(189);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '|' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(198);
      END_STATE();
    case 167:
      ACCEPT_TOKEN(sym_table_cell);
      if (lookahead == 'e') ADVANCE(184);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '|' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(198);
      END_STATE();
    case 168:
      ACCEPT_TOKEN(sym_table_cell);
      if (lookahead == 'e') ADVANCE(180);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '|' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(198);
      END_STATE();
    case 169:
      ACCEPT_TOKEN(sym_table_cell);
      if (lookahead == 'e') ADVANCE(181);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '|' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(198);
      END_STATE();
    case 170:
      ACCEPT_TOKEN(sym_table_cell);
      if (lookahead == 'e') ADVANCE(182);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '|' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(198);
      END_STATE();
    case 171:
      ACCEPT_TOKEN(sym_table_cell);
      if (lookahead == 'h') ADVANCE(168);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '|' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(198);
      END_STATE();
    case 172:
      ACCEPT_TOKEN(sym_table_cell);
      if (lookahead == 'h') ADVANCE(169);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '|' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(198);
      END_STATE();
    case 173:
      ACCEPT_TOKEN(sym_table_cell);
      if (lookahead == 'i') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '|' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(198);
      END_STATE();
    case 174:
      ACCEPT_TOKEN(sym_table_cell);
      if (lookahead == 'i') ADVANCE(186);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '|' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(198);
      END_STATE();
    case 175:
      ACCEPT_TOKEN(sym_table_cell);
      if (lookahead == 'i') ADVANCE(185);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '|' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(198);
      END_STATE();
    case 176:
      ACCEPT_TOKEN(sym_table_cell);
      if (lookahead == 'l') ADVANCE(164);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '|' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(198);
      END_STATE();
    case 177:
      ACCEPT_TOKEN(sym_table_cell);
      if (lookahead == 'l') ADVANCE(175);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '|' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(198);
      END_STATE();
    case 178:
      ACCEPT_TOKEN(sym_table_cell);
      if (lookahead == 'l') ADVANCE(166);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '|' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(198);
      END_STATE();
    case 179:
      ACCEPT_TOKEN(sym_table_cell);
      if (lookahead == 'm') ADVANCE(187);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '|' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(198);
      END_STATE();
    case 180:
      ACCEPT_TOKEN(sym_table_cell);
      if (lookahead == 'n') ADVANCE(81);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '|' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(198);
      END_STATE();
    case 181:
      ACCEPT_TOKEN(sym_table_cell);
      if (lookahead == 'n') ADVANCE(80);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '|' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(198);
      END_STATE();
    case 182:
      ACCEPT_TOKEN(sym_table_cell);
      if (lookahead == 'n') ADVANCE(79);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '|' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(198);
      END_STATE();
    case 183:
      ACCEPT_TOKEN(sym_table_cell);
      if (lookahead == 'n') ADVANCE(163);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '|' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(198);
      END_STATE();
    case 184:
      ACCEPT_TOKEN(sym_table_cell);
      if (lookahead == 'n') ADVANCE(161);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '|' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(198);
      END_STATE();
    case 185:
      ACCEPT_TOKEN(sym_table_cell);
      if (lookahead == 'n') ADVANCE(165);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '|' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(198);
      END_STATE();
    case 186:
      ACCEPT_TOKEN(sym_table_cell);
      if (lookahead == 'o') ADVANCE(76);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '|' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(198);
      END_STATE();
    case 187:
      ACCEPT_TOKEN(sym_table_cell);
      if (lookahead == 'p') ADVANCE(178);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '|' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(198);
      END_STATE();
    case 188:
      ACCEPT_TOKEN(sym_table_cell);
      if (lookahead == 'r') ADVANCE(174);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '|' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(198);
      END_STATE();
    case 189:
      ACCEPT_TOKEN(sym_table_cell);
      if (lookahead == 's') ADVANCE(78);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '|' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(198);
      END_STATE();
    case 190:
      ACCEPT_TOKEN(sym_table_cell);
      if (lookahead == 't') ADVANCE(83);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '|' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(198);
      END_STATE();
    case 191:
      ACCEPT_TOKEN(sym_table_cell);
      if (lookahead == 't') ADVANCE(177);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '|' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(198);
      END_STATE();
    case 192:
      ACCEPT_TOKEN(sym_table_cell);
      if (lookahead == 'u') ADVANCE(190);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '|' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(198);
      END_STATE();
    case 193:
      ACCEPT_TOKEN(sym_table_cell);
      if (lookahead == 'u') ADVANCE(176);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '|' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(198);
      END_STATE();
    case 194:
      ACCEPT_TOKEN(sym_table_cell);
      if (lookahead == 'u') ADVANCE(191);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '|' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(198);
      END_STATE();
    case 195:
      ACCEPT_TOKEN(sym_table_cell);
      if (lookahead == 'v') ADVANCE(170);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '|' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(198);
      END_STATE();
    case 196:
      ACCEPT_TOKEN(sym_table_cell);
      if (lookahead == 'x') ADVANCE(160);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '|' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(198);
      END_STATE();
    case 197:
      ACCEPT_TOKEN(sym_table_cell);
      if (lookahead == '|') ADVANCE(68);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(198);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(67);
      END_STATE();
    case 198:
      ACCEPT_TOKEN(sym_table_cell);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '|' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(198);
      END_STATE();
    case 199:
      ACCEPT_TOKEN(sym_table_cell);
      if (eof) ADVANCE(64);
      if (lookahead == '\n') SKIP(199);
      if (lookahead == '#') ADVANCE(65);
      if (lookahead == '*') ADVANCE(84);
      if (lookahead == '@') ADVANCE(197);
      if (lookahead == 'A') ADVANCE(183);
      if (lookahead == 'B') ADVANCE(192);
      if (lookahead == 'E') ADVANCE(196);
      if (lookahead == 'G') ADVANCE(173);
      if (lookahead == 'R') ADVANCE(193);
      if (lookahead == 'S') ADVANCE(162);
      if (lookahead == 'T') ADVANCE(171);
      if (lookahead == 'W') ADVANCE(172);
      if (lookahead == '|') ADVANCE(154);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(155);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(198);
      END_STATE();
    case 200:
      ACCEPT_TOKEN(sym_table_cell);
      if (eof) ADVANCE(64);
      if (lookahead == '\n') SKIP(200);
      if (lookahead == '#') ADVANCE(65);
      if (lookahead == '*') ADVANCE(84);
      if (lookahead == '@') ADVANCE(197);
      if (lookahead == 'A') ADVANCE(183);
      if (lookahead == 'B') ADVANCE(192);
      if (lookahead == 'G') ADVANCE(173);
      if (lookahead == 'R') ADVANCE(193);
      if (lookahead == 'S') ADVANCE(162);
      if (lookahead == 'T') ADVANCE(171);
      if (lookahead == 'W') ADVANCE(172);
      if (lookahead == '|') ADVANCE(154);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(156);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(198);
      END_STATE();
    case 201:
      ACCEPT_TOKEN(sym_table_cell);
      if (eof) ADVANCE(64);
      if (lookahead == '\n') SKIP(201);
      if (lookahead == '#') ADVANCE(65);
      if (lookahead == '@') ADVANCE(197);
      if (lookahead == 'R') ADVANCE(193);
      if (lookahead == 'S') ADVANCE(162);
      if (lookahead == '|') ADVANCE(154);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(157);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(198);
      END_STATE();
    case 202:
      ACCEPT_TOKEN(sym_doc_string);
      if (lookahead == '"') ADVANCE(202);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(8);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 123},
  [9] = {.lex_state = 62},
  [10] = {.lex_state = 199},
  [11] = {.lex_state = 199},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 200},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 200},
  [23] = {.lex_state = 199},
  [24] = {.lex_state = 200},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 63},
  [35] = {.lex_state = 62},
  [36] = {.lex_state = 63},
  [37] = {.lex_state = 62},
  [38] = {.lex_state = 201},
  [39] = {.lex_state = 201},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 201},
  [42] = {.lex_state = 63},
  [43] = {.lex_state = 63},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 88},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 158},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 158},
  [60] = {.lex_state = 158},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 89},
  [63] = {.lex_state = 89},
  [64] = {.lex_state = 89},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 89},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 3},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 89},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 3},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 3},
  [81] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_tag] = ACTIONS(1),
    [anon_sym_Feature] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_Rule] = ACTIONS(1),
    [anon_sym_Background] = ACTIONS(1),
    [anon_sym_Scenario] = ACTIONS(1),
    [anon_sym_ScenarioOutline] = ACTIONS(1),
    [anon_sym_Examples] = ACTIONS(1),
    [anon_sym_Given] = ACTIONS(1),
    [anon_sym_When] = ACTIONS(1),
    [anon_sym_Then] = ACTIONS(1),
    [anon_sym_And] = ACTIONS(1),
    [anon_sym_But] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [sym_doc_string] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(75),
    [sym_tag_list] = STATE(58),
    [sym_feature] = STATE(68),
    [aux_sym_tag_list_repeat1] = STATE(44),
    [sym_comment] = ACTIONS(3),
    [sym_tag] = ACTIONS(5),
    [anon_sym_Feature] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_Scenario,
    ACTIONS(13), 1,
      anon_sym_PIPE,
    ACTIONS(15), 1,
      sym_doc_string,
    STATE(26), 1,
      sym_data_table,
    STATE(12), 2,
      sym_table_row,
      aux_sym_data_table_repeat1,
    ACTIONS(9), 11,
      ts_builtin_sym_end,
      sym_tag,
      anon_sym_Rule,
      anon_sym_ScenarioOutline,
      anon_sym_Examples,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
      anon_sym_And,
      anon_sym_But,
      anon_sym_STAR,
  [33] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_Scenario,
    ACTIONS(15), 1,
      sym_doc_string,
    ACTIONS(17), 1,
      anon_sym_PIPE,
    STATE(26), 1,
      sym_data_table,
    STATE(20), 2,
      sym_table_row,
      aux_sym_data_table_repeat1,
    ACTIONS(9), 10,
      ts_builtin_sym_end,
      sym_tag,
      anon_sym_Rule,
      anon_sym_ScenarioOutline,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
      anon_sym_And,
      anon_sym_But,
      anon_sym_STAR,
  [65] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_Scenario,
    ACTIONS(23), 1,
      anon_sym_Examples,
    STATE(50), 1,
      sym_examples,
    STATE(80), 1,
      sym_step_keyword,
    STATE(5), 2,
      sym_step,
      aux_sym_background_repeat1,
    ACTIONS(19), 4,
      ts_builtin_sym_end,
      sym_tag,
      anon_sym_Rule,
      anon_sym_ScenarioOutline,
    ACTIONS(25), 6,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
      anon_sym_And,
      anon_sym_But,
      anon_sym_STAR,
  [99] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_Examples,
    ACTIONS(29), 1,
      anon_sym_Scenario,
    STATE(49), 1,
      sym_examples,
    STATE(80), 1,
      sym_step_keyword,
    STATE(14), 2,
      sym_step,
      aux_sym_background_repeat1,
    ACTIONS(27), 4,
      ts_builtin_sym_end,
      sym_tag,
      anon_sym_Rule,
      anon_sym_ScenarioOutline,
    ACTIONS(25), 6,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
      anon_sym_And,
      anon_sym_But,
      anon_sym_STAR,
  [133] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_Examples,
    ACTIONS(33), 1,
      anon_sym_Scenario,
    STATE(48), 1,
      sym_examples,
    STATE(80), 1,
      sym_step_keyword,
    STATE(7), 2,
      sym_step,
      aux_sym_background_repeat1,
    ACTIONS(31), 4,
      ts_builtin_sym_end,
      sym_tag,
      anon_sym_Rule,
      anon_sym_ScenarioOutline,
    ACTIONS(25), 6,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
      anon_sym_And,
      anon_sym_But,
      anon_sym_STAR,
  [167] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_Examples,
    ACTIONS(37), 1,
      anon_sym_Scenario,
    STATE(53), 1,
      sym_examples,
    STATE(80), 1,
      sym_step_keyword,
    STATE(14), 2,
      sym_step,
      aux_sym_background_repeat1,
    ACTIONS(35), 4,
      ts_builtin_sym_end,
      sym_tag,
      anon_sym_Rule,
      anon_sym_ScenarioOutline,
    ACTIONS(25), 6,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
      anon_sym_And,
      anon_sym_But,
      anon_sym_STAR,
  [201] = 7,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
    ACTIONS(41), 1,
      sym_comment,
    ACTIONS(47), 1,
      sym_name_line,
    STATE(78), 1,
      sym_step_keyword,
    STATE(15), 2,
      sym_step,
      aux_sym_background_repeat1,
    ACTIONS(43), 4,
      sym_tag,
      anon_sym_Rule,
      anon_sym_Scenario,
      anon_sym_ScenarioOutline,
    ACTIONS(45), 6,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
      anon_sym_And,
      anon_sym_But,
      anon_sym_STAR,
  [232] = 13,
    ACTIONS(41), 1,
      sym_comment,
    ACTIONS(49), 1,
      ts_builtin_sym_end,
    ACTIONS(51), 1,
      sym_tag,
    ACTIONS(53), 1,
      anon_sym_Rule,
    ACTIONS(55), 1,
      anon_sym_Background,
    ACTIONS(59), 1,
      sym_description_line,
    STATE(25), 1,
      sym_description,
    STATE(32), 1,
      sym_background,
    STATE(35), 1,
      aux_sym_description_repeat1,
    STATE(44), 1,
      aux_sym_tag_list_repeat1,
    STATE(56), 1,
      sym_tag_list,
    ACTIONS(57), 2,
      anon_sym_Scenario,
      anon_sym_ScenarioOutline,
    STATE(28), 3,
      sym_rule_header,
      sym_scenario,
      aux_sym_feature_repeat1,
  [275] = 5,
    ACTIONS(41), 1,
      sym_comment,
    ACTIONS(61), 1,
      ts_builtin_sym_end,
    ACTIONS(65), 1,
      sym_table_cell,
    STATE(10), 1,
      aux_sym_table_row_repeat1,
    ACTIONS(63), 12,
      sym_tag,
      anon_sym_Rule,
      anon_sym_Scenario,
      anon_sym_ScenarioOutline,
      anon_sym_Examples,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
      anon_sym_And,
      anon_sym_But,
      anon_sym_STAR,
      anon_sym_PIPE,
  [302] = 5,
    ACTIONS(41), 1,
      sym_comment,
    ACTIONS(68), 1,
      ts_builtin_sym_end,
    ACTIONS(72), 1,
      sym_table_cell,
    STATE(10), 1,
      aux_sym_table_row_repeat1,
    ACTIONS(70), 12,
      sym_tag,
      anon_sym_Rule,
      anon_sym_Scenario,
      anon_sym_ScenarioOutline,
      anon_sym_Examples,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
      anon_sym_And,
      anon_sym_But,
      anon_sym_STAR,
      anon_sym_PIPE,
  [329] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_PIPE,
    ACTIONS(76), 1,
      anon_sym_Scenario,
    STATE(13), 2,
      sym_table_row,
      aux_sym_data_table_repeat1,
    ACTIONS(74), 11,
      ts_builtin_sym_end,
      sym_tag,
      anon_sym_Rule,
      anon_sym_ScenarioOutline,
      anon_sym_Examples,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
      anon_sym_And,
      anon_sym_But,
      anon_sym_STAR,
  [356] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      anon_sym_Scenario,
    ACTIONS(82), 1,
      anon_sym_PIPE,
    STATE(13), 2,
      sym_table_row,
      aux_sym_data_table_repeat1,
    ACTIONS(78), 11,
      ts_builtin_sym_end,
      sym_tag,
      anon_sym_Rule,
      anon_sym_ScenarioOutline,
      anon_sym_Examples,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
      anon_sym_And,
      anon_sym_But,
      anon_sym_STAR,
  [383] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 1,
      anon_sym_Scenario,
    STATE(80), 1,
      sym_step_keyword,
    STATE(14), 2,
      sym_step,
      aux_sym_background_repeat1,
    ACTIONS(85), 5,
      ts_builtin_sym_end,
      sym_tag,
      anon_sym_Rule,
      anon_sym_ScenarioOutline,
      anon_sym_Examples,
    ACTIONS(89), 6,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
      anon_sym_And,
      anon_sym_But,
      anon_sym_STAR,
  [412] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 1,
      anon_sym_Scenario,
    STATE(78), 1,
      sym_step_keyword,
    STATE(18), 2,
      sym_step,
      aux_sym_background_repeat1,
    ACTIONS(92), 4,
      ts_builtin_sym_end,
      sym_tag,
      anon_sym_Rule,
      anon_sym_ScenarioOutline,
    ACTIONS(25), 6,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
      anon_sym_And,
      anon_sym_But,
      anon_sym_STAR,
  [440] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 1,
      anon_sym_Scenario,
    STATE(78), 1,
      sym_step_keyword,
    STATE(17), 2,
      sym_step,
      aux_sym_background_repeat1,
    ACTIONS(96), 4,
      ts_builtin_sym_end,
      sym_tag,
      anon_sym_Rule,
      anon_sym_ScenarioOutline,
    ACTIONS(25), 6,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
      anon_sym_And,
      anon_sym_But,
      anon_sym_STAR,
  [468] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 1,
      anon_sym_Scenario,
    STATE(78), 1,
      sym_step_keyword,
    STATE(18), 2,
      sym_step,
      aux_sym_background_repeat1,
    ACTIONS(100), 4,
      ts_builtin_sym_end,
      sym_tag,
      anon_sym_Rule,
      anon_sym_ScenarioOutline,
    ACTIONS(25), 6,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
      anon_sym_And,
      anon_sym_But,
      anon_sym_STAR,
  [496] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 1,
      anon_sym_Scenario,
    STATE(78), 1,
      sym_step_keyword,
    STATE(18), 2,
      sym_step,
      aux_sym_background_repeat1,
    ACTIONS(85), 4,
      ts_builtin_sym_end,
      sym_tag,
      anon_sym_Rule,
      anon_sym_ScenarioOutline,
    ACTIONS(89), 6,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
      anon_sym_And,
      anon_sym_But,
      anon_sym_STAR,
  [524] = 5,
    ACTIONS(41), 1,
      sym_comment,
    ACTIONS(68), 1,
      ts_builtin_sym_end,
    ACTIONS(104), 1,
      sym_table_cell,
    STATE(22), 1,
      aux_sym_table_row_repeat1,
    ACTIONS(70), 11,
      sym_tag,
      anon_sym_Rule,
      anon_sym_Scenario,
      anon_sym_ScenarioOutline,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
      anon_sym_And,
      anon_sym_But,
      anon_sym_STAR,
      anon_sym_PIPE,
  [550] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_PIPE,
    ACTIONS(76), 1,
      anon_sym_Scenario,
    STATE(21), 2,
      sym_table_row,
      aux_sym_data_table_repeat1,
    ACTIONS(74), 10,
      ts_builtin_sym_end,
      sym_tag,
      anon_sym_Rule,
      anon_sym_ScenarioOutline,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
      anon_sym_And,
      anon_sym_But,
      anon_sym_STAR,
  [576] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      anon_sym_Scenario,
    ACTIONS(106), 1,
      anon_sym_PIPE,
    STATE(21), 2,
      sym_table_row,
      aux_sym_data_table_repeat1,
    ACTIONS(78), 10,
      ts_builtin_sym_end,
      sym_tag,
      anon_sym_Rule,
      anon_sym_ScenarioOutline,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
      anon_sym_And,
      anon_sym_But,
      anon_sym_STAR,
  [602] = 5,
    ACTIONS(41), 1,
      sym_comment,
    ACTIONS(61), 1,
      ts_builtin_sym_end,
    ACTIONS(109), 1,
      sym_table_cell,
    STATE(22), 1,
      aux_sym_table_row_repeat1,
    ACTIONS(63), 11,
      sym_tag,
      anon_sym_Rule,
      anon_sym_Scenario,
      anon_sym_ScenarioOutline,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
      anon_sym_And,
      anon_sym_But,
      anon_sym_STAR,
      anon_sym_PIPE,
  [628] = 3,
    ACTIONS(41), 1,
      sym_comment,
    ACTIONS(61), 1,
      ts_builtin_sym_end,
    ACTIONS(63), 13,
      sym_tag,
      anon_sym_Rule,
      anon_sym_Scenario,
      anon_sym_ScenarioOutline,
      anon_sym_Examples,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
      anon_sym_And,
      anon_sym_But,
      anon_sym_STAR,
      anon_sym_PIPE,
      sym_table_cell,
  [650] = 3,
    ACTIONS(41), 1,
      sym_comment,
    ACTIONS(61), 1,
      ts_builtin_sym_end,
    ACTIONS(63), 12,
      sym_tag,
      anon_sym_Rule,
      anon_sym_Scenario,
      anon_sym_ScenarioOutline,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
      anon_sym_And,
      anon_sym_But,
      anon_sym_STAR,
      anon_sym_PIPE,
      sym_table_cell,
  [671] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym_tag,
    ACTIONS(57), 1,
      anon_sym_Scenario,
    ACTIONS(112), 1,
      ts_builtin_sym_end,
    ACTIONS(114), 1,
      anon_sym_Rule,
    ACTIONS(116), 1,
      anon_sym_Background,
    ACTIONS(118), 1,
      anon_sym_ScenarioOutline,
    STATE(31), 1,
      sym_background,
    STATE(44), 1,
      aux_sym_tag_list_repeat1,
    STATE(56), 1,
      sym_tag_list,
    STATE(27), 3,
      sym_rule_header,
      sym_scenario,
      aux_sym_feature_repeat1,
  [707] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(122), 1,
      anon_sym_Scenario,
    ACTIONS(120), 11,
      ts_builtin_sym_end,
      sym_tag,
      anon_sym_Rule,
      anon_sym_ScenarioOutline,
      anon_sym_Examples,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
      anon_sym_And,
      anon_sym_But,
      anon_sym_STAR,
  [727] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym_tag,
    ACTIONS(57), 1,
      anon_sym_Scenario,
    ACTIONS(114), 1,
      anon_sym_Rule,
    ACTIONS(118), 1,
      anon_sym_ScenarioOutline,
    ACTIONS(124), 1,
      ts_builtin_sym_end,
    STATE(44), 1,
      aux_sym_tag_list_repeat1,
    STATE(56), 1,
      sym_tag_list,
    STATE(30), 3,
      sym_rule_header,
      sym_scenario,
      aux_sym_feature_repeat1,
  [757] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym_tag,
    ACTIONS(57), 1,
      anon_sym_Scenario,
    ACTIONS(112), 1,
      ts_builtin_sym_end,
    ACTIONS(114), 1,
      anon_sym_Rule,
    ACTIONS(118), 1,
      anon_sym_ScenarioOutline,
    STATE(44), 1,
      aux_sym_tag_list_repeat1,
    STATE(56), 1,
      sym_tag_list,
    STATE(30), 3,
      sym_rule_header,
      sym_scenario,
      aux_sym_feature_repeat1,
  [787] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym_tag,
    ACTIONS(57), 1,
      anon_sym_Scenario,
    ACTIONS(114), 1,
      anon_sym_Rule,
    ACTIONS(118), 1,
      anon_sym_ScenarioOutline,
    ACTIONS(126), 1,
      ts_builtin_sym_end,
    STATE(44), 1,
      aux_sym_tag_list_repeat1,
    STATE(56), 1,
      sym_tag_list,
    STATE(30), 3,
      sym_rule_header,
      sym_scenario,
      aux_sym_feature_repeat1,
  [817] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(128), 1,
      ts_builtin_sym_end,
    ACTIONS(130), 1,
      sym_tag,
    ACTIONS(133), 1,
      anon_sym_Rule,
    ACTIONS(136), 1,
      anon_sym_Scenario,
    ACTIONS(139), 1,
      anon_sym_ScenarioOutline,
    STATE(44), 1,
      aux_sym_tag_list_repeat1,
    STATE(56), 1,
      sym_tag_list,
    STATE(30), 3,
      sym_rule_header,
      sym_scenario,
      aux_sym_feature_repeat1,
  [847] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym_tag,
    ACTIONS(57), 1,
      anon_sym_Scenario,
    ACTIONS(114), 1,
      anon_sym_Rule,
    ACTIONS(118), 1,
      anon_sym_ScenarioOutline,
    ACTIONS(124), 1,
      ts_builtin_sym_end,
    STATE(44), 1,
      aux_sym_tag_list_repeat1,
    STATE(56), 1,
      sym_tag_list,
    STATE(29), 3,
      sym_rule_header,
      sym_scenario,
      aux_sym_feature_repeat1,
  [877] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym_tag,
    ACTIONS(57), 1,
      anon_sym_Scenario,
    ACTIONS(112), 1,
      ts_builtin_sym_end,
    ACTIONS(114), 1,
      anon_sym_Rule,
    ACTIONS(118), 1,
      anon_sym_ScenarioOutline,
    STATE(44), 1,
      aux_sym_tag_list_repeat1,
    STATE(56), 1,
      sym_tag_list,
    STATE(27), 3,
      sym_rule_header,
      sym_scenario,
      aux_sym_feature_repeat1,
  [907] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      anon_sym_Scenario,
    ACTIONS(142), 1,
      anon_sym_PIPE,
    STATE(33), 2,
      sym_table_row,
      aux_sym_data_table_repeat1,
    ACTIONS(78), 4,
      ts_builtin_sym_end,
      sym_tag,
      anon_sym_Rule,
      anon_sym_ScenarioOutline,
  [927] = 6,
    ACTIONS(41), 1,
      sym_comment,
    ACTIONS(145), 1,
      ts_builtin_sym_end,
    ACTIONS(149), 1,
      sym_description_line,
    STATE(42), 1,
      aux_sym_description_repeat1,
    STATE(51), 1,
      sym_description,
    ACTIONS(147), 4,
      sym_tag,
      anon_sym_Rule,
      anon_sym_Scenario,
      anon_sym_ScenarioOutline,
  [949] = 5,
    ACTIONS(41), 1,
      sym_comment,
    ACTIONS(151), 1,
      ts_builtin_sym_end,
    ACTIONS(155), 1,
      sym_description_line,
    STATE(37), 1,
      aux_sym_description_repeat1,
    ACTIONS(153), 5,
      sym_tag,
      anon_sym_Rule,
      anon_sym_Background,
      anon_sym_Scenario,
      anon_sym_ScenarioOutline,
  [969] = 6,
    ACTIONS(41), 1,
      sym_comment,
    ACTIONS(149), 1,
      sym_description_line,
    ACTIONS(157), 1,
      ts_builtin_sym_end,
    STATE(42), 1,
      aux_sym_description_repeat1,
    STATE(46), 1,
      sym_description,
    ACTIONS(159), 4,
      sym_tag,
      anon_sym_Rule,
      anon_sym_Scenario,
      anon_sym_ScenarioOutline,
  [991] = 5,
    ACTIONS(41), 1,
      sym_comment,
    ACTIONS(161), 1,
      ts_builtin_sym_end,
    ACTIONS(165), 1,
      sym_description_line,
    STATE(37), 1,
      aux_sym_description_repeat1,
    ACTIONS(163), 5,
      sym_tag,
      anon_sym_Rule,
      anon_sym_Background,
      anon_sym_Scenario,
      anon_sym_ScenarioOutline,
  [1011] = 5,
    ACTIONS(41), 1,
      sym_comment,
    ACTIONS(61), 1,
      ts_builtin_sym_end,
    ACTIONS(168), 1,
      sym_table_cell,
    STATE(38), 1,
      aux_sym_table_row_repeat1,
    ACTIONS(63), 5,
      sym_tag,
      anon_sym_Rule,
      anon_sym_Scenario,
      anon_sym_ScenarioOutline,
      anon_sym_PIPE,
  [1031] = 5,
    ACTIONS(41), 1,
      sym_comment,
    ACTIONS(68), 1,
      ts_builtin_sym_end,
    ACTIONS(171), 1,
      sym_table_cell,
    STATE(38), 1,
      aux_sym_table_row_repeat1,
    ACTIONS(70), 5,
      sym_tag,
      anon_sym_Rule,
      anon_sym_Scenario,
      anon_sym_ScenarioOutline,
      anon_sym_PIPE,
  [1051] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 1,
      anon_sym_Scenario,
    ACTIONS(173), 1,
      anon_sym_PIPE,
    STATE(33), 2,
      sym_table_row,
      aux_sym_data_table_repeat1,
    ACTIONS(74), 4,
      ts_builtin_sym_end,
      sym_tag,
      anon_sym_Rule,
      anon_sym_ScenarioOutline,
  [1071] = 3,
    ACTIONS(41), 1,
      sym_comment,
    ACTIONS(61), 1,
      ts_builtin_sym_end,
    ACTIONS(63), 6,
      sym_tag,
      anon_sym_Rule,
      anon_sym_Scenario,
      anon_sym_ScenarioOutline,
      anon_sym_PIPE,
      sym_table_cell,
  [1086] = 5,
    ACTIONS(41), 1,
      sym_comment,
    ACTIONS(151), 1,
      ts_builtin_sym_end,
    ACTIONS(175), 1,
      sym_description_line,
    STATE(43), 1,
      aux_sym_description_repeat1,
    ACTIONS(153), 4,
      sym_tag,
      anon_sym_Rule,
      anon_sym_Scenario,
      anon_sym_ScenarioOutline,
  [1105] = 5,
    ACTIONS(41), 1,
      sym_comment,
    ACTIONS(161), 1,
      ts_builtin_sym_end,
    ACTIONS(177), 1,
      sym_description_line,
    STATE(43), 1,
      aux_sym_description_repeat1,
    ACTIONS(163), 4,
      sym_tag,
      anon_sym_Rule,
      anon_sym_Scenario,
      anon_sym_ScenarioOutline,
  [1124] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 1,
      sym_tag,
    ACTIONS(184), 1,
      anon_sym_Scenario,
    STATE(45), 1,
      aux_sym_tag_list_repeat1,
    ACTIONS(182), 3,
      anon_sym_Feature,
      anon_sym_Rule,
      anon_sym_ScenarioOutline,
  [1142] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      sym_tag,
    ACTIONS(191), 1,
      anon_sym_Scenario,
    STATE(45), 1,
      aux_sym_tag_list_repeat1,
    ACTIONS(189), 3,
      anon_sym_Feature,
      anon_sym_Rule,
      anon_sym_ScenarioOutline,
  [1160] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 1,
      anon_sym_Scenario,
    ACTIONS(193), 4,
      ts_builtin_sym_end,
      sym_tag,
      anon_sym_Rule,
      anon_sym_ScenarioOutline,
  [1173] = 5,
    ACTIONS(41), 1,
      sym_comment,
    ACTIONS(197), 1,
      sym_name_line,
    ACTIONS(199), 1,
      anon_sym_PIPE,
    STATE(54), 1,
      sym_data_table,
    STATE(40), 2,
      sym_table_row,
      aux_sym_data_table_repeat1,
  [1190] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 1,
      anon_sym_Scenario,
    ACTIONS(35), 4,
      ts_builtin_sym_end,
      sym_tag,
      anon_sym_Rule,
      anon_sym_ScenarioOutline,
  [1203] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 1,
      anon_sym_Scenario,
    ACTIONS(201), 4,
      ts_builtin_sym_end,
      sym_tag,
      anon_sym_Rule,
      anon_sym_ScenarioOutline,
  [1216] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      anon_sym_Scenario,
    ACTIONS(27), 4,
      ts_builtin_sym_end,
      sym_tag,
      anon_sym_Rule,
      anon_sym_ScenarioOutline,
  [1229] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(207), 1,
      anon_sym_Scenario,
    ACTIONS(205), 4,
      ts_builtin_sym_end,
      sym_tag,
      anon_sym_Rule,
      anon_sym_ScenarioOutline,
  [1242] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(211), 1,
      anon_sym_Scenario,
    ACTIONS(209), 4,
      ts_builtin_sym_end,
      sym_tag,
      anon_sym_Rule,
      anon_sym_ScenarioOutline,
  [1255] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 1,
      anon_sym_Scenario,
    ACTIONS(213), 4,
      ts_builtin_sym_end,
      sym_tag,
      anon_sym_Rule,
      anon_sym_ScenarioOutline,
  [1268] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 1,
      anon_sym_Scenario,
    ACTIONS(217), 4,
      ts_builtin_sym_end,
      sym_tag,
      anon_sym_Rule,
      anon_sym_ScenarioOutline,
  [1281] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 1,
      anon_sym_PIPE,
    STATE(52), 1,
      sym_data_table,
    STATE(40), 2,
      sym_table_row,
      aux_sym_data_table_repeat1,
  [1295] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(221), 1,
      anon_sym_Rule,
    ACTIONS(223), 1,
      anon_sym_Scenario,
    ACTIONS(225), 1,
      anon_sym_ScenarioOutline,
  [1308] = 3,
    ACTIONS(41), 1,
      sym_comment,
    ACTIONS(104), 1,
      sym_table_cell,
    STATE(19), 1,
      aux_sym_table_row_repeat1,
  [1318] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_Feature,
    STATE(72), 1,
      sym_feature,
  [1328] = 3,
    ACTIONS(41), 1,
      sym_comment,
    ACTIONS(72), 1,
      sym_table_cell,
    STATE(11), 1,
      aux_sym_table_row_repeat1,
  [1338] = 3,
    ACTIONS(41), 1,
      sym_comment,
    ACTIONS(171), 1,
      sym_table_cell,
    STATE(39), 1,
      aux_sym_table_row_repeat1,
  [1348] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 1,
      anon_sym_COLON,
  [1355] = 2,
    ACTIONS(41), 1,
      sym_comment,
    ACTIONS(229), 1,
      sym_name_line,
  [1362] = 2,
    ACTIONS(41), 1,
      sym_comment,
    ACTIONS(231), 1,
      sym_name_line,
  [1369] = 2,
    ACTIONS(41), 1,
      sym_comment,
    ACTIONS(233), 1,
      sym_name_line,
  [1376] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(235), 1,
      anon_sym_PIPE,
  [1383] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 1,
      anon_sym_COLON,
  [1390] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(239), 1,
      anon_sym_COLON,
  [1397] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 1,
      ts_builtin_sym_end,
  [1404] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 1,
      anon_sym_COLON,
  [1411] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(245), 1,
      anon_sym_COLON,
  [1418] = 2,
    ACTIONS(41), 1,
      sym_comment,
    ACTIONS(247), 1,
      sym_name_line,
  [1425] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(249), 1,
      ts_builtin_sym_end,
  [1432] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 1,
      anon_sym_PIPE,
  [1439] = 2,
    ACTIONS(41), 1,
      sym_comment,
    ACTIONS(253), 1,
      sym_step_text,
  [1446] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(255), 1,
      ts_builtin_sym_end,
  [1453] = 2,
    ACTIONS(41), 1,
      sym_comment,
    ACTIONS(257), 1,
      sym_name_line,
  [1460] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(259), 1,
      anon_sym_PIPE,
  [1467] = 2,
    ACTIONS(41), 1,
      sym_comment,
    ACTIONS(261), 1,
      sym_step_text,
  [1474] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(263), 1,
      anon_sym_COLON,
  [1481] = 2,
    ACTIONS(41), 1,
      sym_comment,
    ACTIONS(265), 1,
      sym_step_text,
  [1488] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(267), 1,
      anon_sym_COLON,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 33,
  [SMALL_STATE(4)] = 65,
  [SMALL_STATE(5)] = 99,
  [SMALL_STATE(6)] = 133,
  [SMALL_STATE(7)] = 167,
  [SMALL_STATE(8)] = 201,
  [SMALL_STATE(9)] = 232,
  [SMALL_STATE(10)] = 275,
  [SMALL_STATE(11)] = 302,
  [SMALL_STATE(12)] = 329,
  [SMALL_STATE(13)] = 356,
  [SMALL_STATE(14)] = 383,
  [SMALL_STATE(15)] = 412,
  [SMALL_STATE(16)] = 440,
  [SMALL_STATE(17)] = 468,
  [SMALL_STATE(18)] = 496,
  [SMALL_STATE(19)] = 524,
  [SMALL_STATE(20)] = 550,
  [SMALL_STATE(21)] = 576,
  [SMALL_STATE(22)] = 602,
  [SMALL_STATE(23)] = 628,
  [SMALL_STATE(24)] = 650,
  [SMALL_STATE(25)] = 671,
  [SMALL_STATE(26)] = 707,
  [SMALL_STATE(27)] = 727,
  [SMALL_STATE(28)] = 757,
  [SMALL_STATE(29)] = 787,
  [SMALL_STATE(30)] = 817,
  [SMALL_STATE(31)] = 847,
  [SMALL_STATE(32)] = 877,
  [SMALL_STATE(33)] = 907,
  [SMALL_STATE(34)] = 927,
  [SMALL_STATE(35)] = 949,
  [SMALL_STATE(36)] = 969,
  [SMALL_STATE(37)] = 991,
  [SMALL_STATE(38)] = 1011,
  [SMALL_STATE(39)] = 1031,
  [SMALL_STATE(40)] = 1051,
  [SMALL_STATE(41)] = 1071,
  [SMALL_STATE(42)] = 1086,
  [SMALL_STATE(43)] = 1105,
  [SMALL_STATE(44)] = 1124,
  [SMALL_STATE(45)] = 1142,
  [SMALL_STATE(46)] = 1160,
  [SMALL_STATE(47)] = 1173,
  [SMALL_STATE(48)] = 1190,
  [SMALL_STATE(49)] = 1203,
  [SMALL_STATE(50)] = 1216,
  [SMALL_STATE(51)] = 1229,
  [SMALL_STATE(52)] = 1242,
  [SMALL_STATE(53)] = 1255,
  [SMALL_STATE(54)] = 1268,
  [SMALL_STATE(55)] = 1281,
  [SMALL_STATE(56)] = 1295,
  [SMALL_STATE(57)] = 1308,
  [SMALL_STATE(58)] = 1318,
  [SMALL_STATE(59)] = 1328,
  [SMALL_STATE(60)] = 1338,
  [SMALL_STATE(61)] = 1348,
  [SMALL_STATE(62)] = 1355,
  [SMALL_STATE(63)] = 1362,
  [SMALL_STATE(64)] = 1369,
  [SMALL_STATE(65)] = 1376,
  [SMALL_STATE(66)] = 1383,
  [SMALL_STATE(67)] = 1390,
  [SMALL_STATE(68)] = 1397,
  [SMALL_STATE(69)] = 1404,
  [SMALL_STATE(70)] = 1411,
  [SMALL_STATE(71)] = 1418,
  [SMALL_STATE(72)] = 1425,
  [SMALL_STATE(73)] = 1432,
  [SMALL_STATE(74)] = 1439,
  [SMALL_STATE(75)] = 1446,
  [SMALL_STATE(76)] = 1453,
  [SMALL_STATE(77)] = 1460,
  [SMALL_STATE(78)] = 1467,
  [SMALL_STATE(79)] = 1474,
  [SMALL_STATE(80)] = 1481,
  [SMALL_STATE(81)] = 1488,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_step, 2, 0, 2),
  [11] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_step, 2, 0, 2),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scenario, 3, 0, 1),
  [21] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scenario, 3, 0, 1),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scenario, 4, 0, 1),
  [29] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scenario, 4, 0, 1),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scenario, 4, 0, 3),
  [33] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scenario, 4, 0, 3),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scenario, 5, 0, 3),
  [37] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scenario, 5, 0, 3),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_background, 2, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_background, 2, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_feature, 3, 0, 1),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_table_row_repeat1, 2, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_table_row_repeat1, 2, 0, 0),
  [65] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_table_row_repeat1, 2, 0, 0), SHIFT_REPEAT(77),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table_row, 2, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_table_row, 2, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_data_table, 1, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_data_table, 1, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_data_table_repeat1, 2, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_data_table_repeat1, 2, 0, 0),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_data_table_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_background_repeat1, 2, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_background_repeat1, 2, 0, 0),
  [89] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_background_repeat1, 2, 0, 0), SHIFT_REPEAT(74),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_background, 3, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_background, 3, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_background, 3, 0, 1),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_background, 3, 0, 1),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_background, 4, 0, 1),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_background, 4, 0, 1),
  [104] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [106] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_data_table_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [109] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_table_row_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_feature, 4, 0, 1),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_step, 3, 0, 2),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_step, 3, 0, 2),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_feature, 5, 0, 1),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_feature, 6, 0, 1),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_feature_repeat1, 2, 0, 0),
  [130] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_feature_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [133] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_feature_repeat1, 2, 0, 0), SHIFT_REPEAT(79),
  [136] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_feature_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [139] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_feature_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [142] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_data_table_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule_header, 4, 0, 3),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_rule_header, 4, 0, 3),
  [149] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_description, 1, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_description, 1, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule_header, 3, 0, 1),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_rule_header, 3, 0, 1),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_description_repeat1, 2, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_description_repeat1, 2, 0, 0),
  [165] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_description_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [168] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_table_row_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [171] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [175] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [177] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_description_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_list, 1, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_list, 1, 0, 0),
  [186] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tag_list_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tag_list_repeat1, 2, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_tag_list_repeat1, 2, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule_header, 4, 0, 1),
  [195] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_rule_header, 4, 0, 1),
  [197] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [199] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scenario, 5, 0, 1),
  [203] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scenario, 5, 0, 1),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule_header, 5, 0, 3),
  [207] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_rule_header, 5, 0, 3),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_examples, 4, 0, 1),
  [211] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_examples, 4, 0, 1),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scenario, 6, 0, 3),
  [215] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scenario, 6, 0, 3),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_examples, 3, 0, 0),
  [219] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_examples, 3, 0, 0),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [223] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [229] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [231] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [233] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [247] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [249] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [253] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_step_keyword, 1, 0, 0),
  [255] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [257] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [261] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [265] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_gherkin(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "gherkin",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
