/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 30
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 26
#define ALIAS_COUNT 0
#define TOKEN_COUNT 15
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_comment = 1,
  sym_tag = 2,
  anon_sym_Feature = 3,
  anon_sym_COLON = 4,
  anon_sym_Scenario = 5,
  anon_sym_Given = 6,
  anon_sym_When = 7,
  anon_sym_Then = 8,
  anon_sym_And = 9,
  anon_sym_But = 10,
  anon_sym_STAR = 11,
  sym_step_text = 12,
  sym_name_line = 13,
  sym_description_line = 14,
  sym_source_file = 15,
  sym_tag_list = 16,
  sym_feature = 17,
  sym_scenario = 18,
  sym_step = 19,
  sym_step_keyword = 20,
  sym_description = 21,
  aux_sym_tag_list_repeat1 = 22,
  aux_sym_feature_repeat1 = 23,
  aux_sym_scenario_repeat1 = 24,
  aux_sym_description_repeat1 = 25,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [sym_tag] = "tag",
  [anon_sym_Feature] = "Feature",
  [anon_sym_COLON] = ":",
  [anon_sym_Scenario] = "Scenario",
  [anon_sym_Given] = "Given",
  [anon_sym_When] = "When",
  [anon_sym_Then] = "Then",
  [anon_sym_And] = "And",
  [anon_sym_But] = "But",
  [anon_sym_STAR] = "*",
  [sym_step_text] = "step_text",
  [sym_name_line] = "name_line",
  [sym_description_line] = "description_line",
  [sym_source_file] = "source_file",
  [sym_tag_list] = "tag_list",
  [sym_feature] = "feature",
  [sym_scenario] = "scenario",
  [sym_step] = "step",
  [sym_step_keyword] = "step_keyword",
  [sym_description] = "description",
  [aux_sym_tag_list_repeat1] = "tag_list_repeat1",
  [aux_sym_feature_repeat1] = "feature_repeat1",
  [aux_sym_scenario_repeat1] = "scenario_repeat1",
  [aux_sym_description_repeat1] = "description_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [sym_tag] = sym_tag,
  [anon_sym_Feature] = anon_sym_Feature,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_Scenario] = anon_sym_Scenario,
  [anon_sym_Given] = anon_sym_Given,
  [anon_sym_When] = anon_sym_When,
  [anon_sym_Then] = anon_sym_Then,
  [anon_sym_And] = anon_sym_And,
  [anon_sym_But] = anon_sym_But,
  [anon_sym_STAR] = anon_sym_STAR,
  [sym_step_text] = sym_step_text,
  [sym_name_line] = sym_name_line,
  [sym_description_line] = sym_description_line,
  [sym_source_file] = sym_source_file,
  [sym_tag_list] = sym_tag_list,
  [sym_feature] = sym_feature,
  [sym_scenario] = sym_scenario,
  [sym_step] = sym_step,
  [sym_step_keyword] = sym_step_keyword,
  [sym_description] = sym_description,
  [aux_sym_tag_list_repeat1] = aux_sym_tag_list_repeat1,
  [aux_sym_feature_repeat1] = aux_sym_feature_repeat1,
  [aux_sym_scenario_repeat1] = aux_sym_scenario_repeat1,
  [aux_sym_description_repeat1] = aux_sym_description_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_Feature] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Scenario] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Given] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_When] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Then] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_And] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_But] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [sym_step_text] = {
    .visible = true,
    .named = true,
  },
  [sym_name_line] = {
    .visible = true,
    .named = true,
  },
  [sym_description_line] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_list] = {
    .visible = true,
    .named = true,
  },
  [sym_feature] = {
    .visible = true,
    .named = true,
  },
  [sym_scenario] = {
    .visible = true,
    .named = true,
  },
  [sym_step] = {
    .visible = true,
    .named = true,
  },
  [sym_step_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_description] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_tag_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_feature_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_scenario_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_description_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_keyword = 1,
  field_name = 2,
  field_text = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_keyword] = "keyword",
  [field_name] = "name",
  [field_text] = "text",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 2},
  [1] =
    {field_name, 3},
  [2] =
    {field_keyword, 0},
    {field_text, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(32);
      ADVANCE_MAP(
        '#', 33,
        '*', 43,
        ':', 36,
        '@', 30,
        'A', 17,
        'B', 27,
        'F', 7,
        'G', 15,
        'S', 5,
        'T', 13,
        'W', 14,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '#') ADVANCE(33);
      if (lookahead == '@') ADVANCE(30);
      if (lookahead == 'S') ADVANCE(50);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(48);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '|' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(57);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(2);
      if (lookahead == '#') ADVANCE(33);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(44);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(45);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(26);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(23);
      END_STATE();
    case 5:
      if (lookahead == 'c') ADVANCE(9);
      END_STATE();
    case 6:
      if (lookahead == 'd') ADVANCE(41);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(3);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(35);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(19);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 13:
      if (lookahead == 'h') ADVANCE(10);
      END_STATE();
    case 14:
      if (lookahead == 'h') ADVANCE(11);
      END_STATE();
    case 15:
      if (lookahead == 'i') ADVANCE(29);
      END_STATE();
    case 16:
      if (lookahead == 'i') ADVANCE(22);
      END_STATE();
    case 17:
      if (lookahead == 'n') ADVANCE(6);
      END_STATE();
    case 18:
      if (lookahead == 'n') ADVANCE(40);
      END_STATE();
    case 19:
      if (lookahead == 'n') ADVANCE(39);
      END_STATE();
    case 20:
      if (lookahead == 'n') ADVANCE(38);
      END_STATE();
    case 21:
      if (lookahead == 'n') ADVANCE(4);
      END_STATE();
    case 22:
      if (lookahead == 'o') ADVANCE(37);
      END_STATE();
    case 23:
      if (lookahead == 'r') ADVANCE(16);
      END_STATE();
    case 24:
      if (lookahead == 'r') ADVANCE(8);
      END_STATE();
    case 25:
      if (lookahead == 't') ADVANCE(42);
      END_STATE();
    case 26:
      if (lookahead == 't') ADVANCE(28);
      END_STATE();
    case 27:
      if (lookahead == 'u') ADVANCE(25);
      END_STATE();
    case 28:
      if (lookahead == 'u') ADVANCE(24);
      END_STATE();
    case 29:
      if (lookahead == 'v') ADVANCE(12);
      END_STATE();
    case 30:
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(34);
      END_STATE();
    case 31:
      if (eof) ADVANCE(32);
      if (lookahead == '\n') SKIP(31);
      if (lookahead == '#') ADVANCE(33);
      if (lookahead == '@') ADVANCE(30);
      if (lookahead == 'S') ADVANCE(50);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(48);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '|' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(57);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_tag);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_Feature);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_Scenario);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_Given);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_When);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_Then);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_And);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_But);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_step_text);
      if (lookahead == '\n') SKIP(2);
      if (lookahead == '#') ADVANCE(33);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(44);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(45);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_step_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead == '\n') SKIP(46);
      if (lookahead == '#') ADVANCE(33);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(46);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(47);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_name_line);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '#') ADVANCE(33);
      if (lookahead == '@') ADVANCE(56);
      if (lookahead == 'S') ADVANCE(50);
      if (lookahead == '"' ||
          lookahead == '|') ADVANCE(57);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(48);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(57);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'a') ADVANCE(55);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(57);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'c') ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(57);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'e') ADVANCE(53);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(57);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'i') ADVANCE(54);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(57);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'n') ADVANCE(49);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(57);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'o') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(57);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'r') ADVANCE(52);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(57);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(57);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(34);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(57);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 31},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 31},
  [14] = {.lex_state = 31},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 46},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 46},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 46},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_tag] = ACTIONS(1),
    [anon_sym_Feature] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_Scenario] = ACTIONS(1),
    [anon_sym_Given] = ACTIONS(1),
    [anon_sym_When] = ACTIONS(1),
    [anon_sym_Then] = ACTIONS(1),
    [anon_sym_And] = ACTIONS(1),
    [anon_sym_But] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(18),
    [sym_tag_list] = STATE(17),
    [sym_feature] = STATE(19),
    [aux_sym_tag_list_repeat1] = STATE(15),
    [sym_comment] = ACTIONS(3),
    [sym_tag] = ACTIONS(5),
    [anon_sym_Feature] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(3), 1,
      sym_comment,
    STATE(27), 1,
      sym_step_keyword,
    STATE(6), 2,
      sym_step,
      aux_sym_scenario_repeat1,
    ACTIONS(9), 3,
      ts_builtin_sym_end,
      sym_tag,
      anon_sym_Scenario,
    ACTIONS(11), 6,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
      anon_sym_And,
      anon_sym_But,
      anon_sym_STAR,
  [24] = 5,
    ACTIONS(3), 1,
      sym_comment,
    STATE(27), 1,
      sym_step_keyword,
    STATE(5), 2,
      sym_step,
      aux_sym_scenario_repeat1,
    ACTIONS(13), 3,
      ts_builtin_sym_end,
      sym_tag,
      anon_sym_Scenario,
    ACTIONS(11), 6,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
      anon_sym_And,
      anon_sym_But,
      anon_sym_STAR,
  [48] = 5,
    ACTIONS(3), 1,
      sym_comment,
    STATE(27), 1,
      sym_step_keyword,
    STATE(3), 2,
      sym_step,
      aux_sym_scenario_repeat1,
    ACTIONS(15), 3,
      ts_builtin_sym_end,
      sym_tag,
      anon_sym_Scenario,
    ACTIONS(11), 6,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
      anon_sym_And,
      anon_sym_But,
      anon_sym_STAR,
  [72] = 5,
    ACTIONS(3), 1,
      sym_comment,
    STATE(27), 1,
      sym_step_keyword,
    STATE(5), 2,
      sym_step,
      aux_sym_scenario_repeat1,
    ACTIONS(17), 3,
      ts_builtin_sym_end,
      sym_tag,
      anon_sym_Scenario,
    ACTIONS(19), 6,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
      anon_sym_And,
      anon_sym_But,
      anon_sym_STAR,
  [96] = 5,
    ACTIONS(3), 1,
      sym_comment,
    STATE(27), 1,
      sym_step_keyword,
    STATE(5), 2,
      sym_step,
      aux_sym_scenario_repeat1,
    ACTIONS(22), 3,
      ts_builtin_sym_end,
      sym_tag,
      anon_sym_Scenario,
    ACTIONS(11), 6,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
      anon_sym_And,
      anon_sym_But,
      anon_sym_STAR,
  [120] = 10,
    ACTIONS(24), 1,
      ts_builtin_sym_end,
    ACTIONS(26), 1,
      sym_comment,
    ACTIONS(28), 1,
      sym_tag,
    ACTIONS(30), 1,
      anon_sym_Scenario,
    ACTIONS(32), 1,
      sym_description_line,
    STATE(9), 1,
      sym_description,
    STATE(13), 1,
      aux_sym_description_repeat1,
    STATE(15), 1,
      aux_sym_tag_list_repeat1,
    STATE(24), 1,
      sym_tag_list,
    STATE(10), 2,
      sym_scenario,
      aux_sym_feature_repeat1,
  [152] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(34), 9,
      ts_builtin_sym_end,
      sym_tag,
      anon_sym_Scenario,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
      anon_sym_And,
      anon_sym_But,
      anon_sym_STAR,
  [167] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym_tag,
    ACTIONS(36), 1,
      ts_builtin_sym_end,
    ACTIONS(38), 1,
      anon_sym_Scenario,
    STATE(15), 1,
      aux_sym_tag_list_repeat1,
    STATE(24), 1,
      sym_tag_list,
    STATE(12), 2,
      sym_scenario,
      aux_sym_feature_repeat1,
  [190] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym_tag,
    ACTIONS(36), 1,
      ts_builtin_sym_end,
    ACTIONS(38), 1,
      anon_sym_Scenario,
    STATE(15), 1,
      aux_sym_tag_list_repeat1,
    STATE(24), 1,
      sym_tag_list,
    STATE(11), 2,
      sym_scenario,
      aux_sym_feature_repeat1,
  [213] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(40), 1,
      ts_builtin_sym_end,
    ACTIONS(42), 1,
      sym_tag,
    ACTIONS(45), 1,
      anon_sym_Scenario,
    STATE(15), 1,
      aux_sym_tag_list_repeat1,
    STATE(24), 1,
      sym_tag_list,
    STATE(11), 2,
      sym_scenario,
      aux_sym_feature_repeat1,
  [236] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym_tag,
    ACTIONS(38), 1,
      anon_sym_Scenario,
    ACTIONS(48), 1,
      ts_builtin_sym_end,
    STATE(15), 1,
      aux_sym_tag_list_repeat1,
    STATE(24), 1,
      sym_tag_list,
    STATE(11), 2,
      sym_scenario,
      aux_sym_feature_repeat1,
  [259] = 5,
    ACTIONS(26), 1,
      sym_comment,
    ACTIONS(50), 1,
      ts_builtin_sym_end,
    ACTIONS(54), 1,
      sym_description_line,
    STATE(14), 1,
      aux_sym_description_repeat1,
    ACTIONS(52), 2,
      sym_tag,
      anon_sym_Scenario,
  [276] = 5,
    ACTIONS(26), 1,
      sym_comment,
    ACTIONS(56), 1,
      ts_builtin_sym_end,
    ACTIONS(60), 1,
      sym_description_line,
    STATE(14), 1,
      aux_sym_description_repeat1,
    ACTIONS(58), 2,
      sym_tag,
      anon_sym_Scenario,
  [293] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 1,
      sym_tag,
    STATE(16), 1,
      aux_sym_tag_list_repeat1,
    ACTIONS(65), 2,
      anon_sym_Feature,
      anon_sym_Scenario,
  [307] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 1,
      sym_tag,
    STATE(16), 1,
      aux_sym_tag_list_repeat1,
    ACTIONS(70), 2,
      anon_sym_Feature,
      anon_sym_Scenario,
  [321] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_Feature,
    STATE(22), 1,
      sym_feature,
  [331] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 1,
      ts_builtin_sym_end,
  [338] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 1,
      ts_builtin_sym_end,
  [345] = 2,
    ACTIONS(26), 1,
      sym_comment,
    ACTIONS(76), 1,
      sym_name_line,
  [352] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 1,
      anon_sym_COLON,
  [359] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      ts_builtin_sym_end,
  [366] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 1,
      anon_sym_COLON,
  [373] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(84), 1,
      anon_sym_Scenario,
  [380] = 2,
    ACTIONS(26), 1,
      sym_comment,
    ACTIONS(86), 1,
      sym_name_line,
  [387] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 1,
      anon_sym_COLON,
  [394] = 2,
    ACTIONS(26), 1,
      sym_comment,
    ACTIONS(90), 1,
      sym_step_text,
  [401] = 2,
    ACTIONS(26), 1,
      sym_comment,
    ACTIONS(92), 1,
      sym_step_text,
  [408] = 2,
    ACTIONS(26), 1,
      sym_comment,
    ACTIONS(94), 1,
      sym_name_line,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 24,
  [SMALL_STATE(4)] = 48,
  [SMALL_STATE(5)] = 72,
  [SMALL_STATE(6)] = 96,
  [SMALL_STATE(7)] = 120,
  [SMALL_STATE(8)] = 152,
  [SMALL_STATE(9)] = 167,
  [SMALL_STATE(10)] = 190,
  [SMALL_STATE(11)] = 213,
  [SMALL_STATE(12)] = 236,
  [SMALL_STATE(13)] = 259,
  [SMALL_STATE(14)] = 276,
  [SMALL_STATE(15)] = 293,
  [SMALL_STATE(16)] = 307,
  [SMALL_STATE(17)] = 321,
  [SMALL_STATE(18)] = 331,
  [SMALL_STATE(19)] = 338,
  [SMALL_STATE(20)] = 345,
  [SMALL_STATE(21)] = 352,
  [SMALL_STATE(22)] = 359,
  [SMALL_STATE(23)] = 366,
  [SMALL_STATE(24)] = 373,
  [SMALL_STATE(25)] = 380,
  [SMALL_STATE(26)] = 387,
  [SMALL_STATE(27)] = 394,
  [SMALL_STATE(28)] = 401,
  [SMALL_STATE(29)] = 408,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scenario, 4, 0, 2),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scenario, 4, 0, 1),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scenario, 3, 0, 1),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_scenario_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_scenario_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [22] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scenario, 5, 0, 2),
  [24] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_feature, 3, 0, 1),
  [26] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [28] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [30] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [32] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_step, 2, 0, 3),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_feature, 4, 0, 1),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_feature_repeat1, 2, 0, 0),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_feature_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_feature_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_feature, 5, 0, 1),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_description, 1, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_description, 1, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_description_repeat1, 2, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_description_repeat1, 2, 0, 0),
  [60] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_description_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_list, 1, 0, 0),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tag_list_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tag_list_repeat1, 2, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [86] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [90] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_step_keyword, 1, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_gherkin(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "gherkin",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
